export type Item={id:string;version:string;subject:string;topic:string;domain:string;grade:number;difficulty:number;format:string;stem:string;options?:{id:string;text:string}[];key:any;steps:string[];why?:Record<string,string>;takeaway:string;verify:any;passage?:{id:string;title:string;genre:string;paragraphs:string[];attribution:string;glossary?:Record<string,string>};setId?:string;evidence?:string;standard?:string;blueprint?:string};
export function rng(seed:number){let x=seed>>>0;return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}}
const gcd=(a:number,b:number):number=>b?gcd(b,a%b):Math.abs(a);
const fraction=(a:number,b:number)=>{let d=gcd(a,b);return b/d===1?String(a/d):`${a/d}/${b/d}`};
export const mathTopics=[
 ['order','Order of operations','Number sense','6.EE',8],['gcf','Factors and multiples','Number sense','6.NS',8],['fractions','Fraction operations','Rational numbers','6.NS',8],['remainder','Fractions of a remainder','Rational numbers','6.NS',8],['signed','Signed rational numbers','Rational numbers','7.NS',8],['absolute','Distance on a number line','Rational numbers','6.NS',8],['ratio','Ratio and proportion','Ratios and rates','7.RP',8],['rate','Unit rates','Ratios and rates','7.RP',8],['speed','Distance, rate, and time','Ratios and rates','6.RP',8],['scale','Scale drawings','Geometry','7.G',8],['percent','Successive percent changes','Percent applications','7.RP',8],['original','Original price','Percent applications','7.RP',8],['interest','Simple interest','Percent applications','7.RP',8],['equation','Two-step equations','Expressions and equations','7.EE',8],['distribute','Distributive property','Expressions and equations','7.EE',8],['inequality','Inequalities','Expressions and equations','7.EE',8],['angles','Angle relationships','Geometry','7.G',8],['area','Composite area','Geometry','7.G',8],['volume','Volume and capacity','Geometry','6.G',8],['surface','Surface area','Geometry','6.G',8],['average','Mean and missing values','Statistics','6.SP',8],['probability','Probability without replacement','Probability','7.SP',8],['counting','Sample spaces','Probability','7.SP',8],['powers','Integer exponent rules','Grade 9 extensions','8.EE',9],['pythagoras','Pythagorean theorem','Grade 9 extensions','8.G',9],['linear','Linear equations','Grade 9 extensions','8.EE',9],['slope','Slope and rate of change','Grade 9 extensions','8.EE',9]
].map(([id,title,domain,standard,grade])=>({id:String(id),title:String(title),domain:String(domain),standard:String(standard),grade:Number(grade),subject:'Math',description:`Practice ${String(title).toLowerCase()} with a worked solution.`,prerequisites:['Understand the quantities and units'],formats:['Single choice','Numeric entry'],alignment:'Domain-level alignment; exact leaf-code audit pending',classification:'Tested-content preparation',publishedCount:0}));
export function mathItem(topic:string,seed:number,difficulty=2,forceFormat?:string):Item{
 const random=rng(seed);const n=(lo:number,hi:number)=>lo+Math.floor(random()*(hi-lo+1));let a=n(2,15),b=n(2,12),c=n(2,8),d=n(2,7),answer:any,stem='',steps:string[]=[],distractors:any[]=[],why:string[]=[];let verify:any={};let standard=mathTopics.find(t=>t.id===topic)?.standard;
 switch(topic){
 case 'order':answer=a+b*c-d;stem=`What is the value of ${a} + ${b} × ${c} − ${d}?`;steps=[`Multiply first: ${b} × ${c} = ${b*c}.`,`Then add and subtract from left to right: ${a} + ${b*c} − ${d} = ${answer}.`];distractors=[(a+b)*c-d,a+b*(c-d),a+b+c-d];why=['Adding before multiplying changes the required order.','Subtracting inside the product invents parentheses.','The multiplication sign cannot be treated as addition.'];verify={kind:'order',a,b,c,d};break;
 case 'gcf':a=n(2,12);b=[2,3,5,7][n(0,3)];c=[4,6,8,9][n(0,3)];answer=gcd(a*b,a*c);stem=`Two rolls contain ${a*b} cm and ${a*c} cm of ribbon. Both are cut into equal pieces with no ribbon left over. What is the greatest possible length, in centimeters, of each piece?`;steps=[`The length must divide both ${a*b} and ${a*c}.`,`The greatest common factor is ${answer}.`,`Check: ${a*b} ÷ ${answer} = ${a*b/answer} and ${a*c} ÷ ${answer} = ${a*c/answer}, both whole numbers.`];distractors=[a*b+a*c,a*b*a*c/answer,1];why=['Adding the lengths does not find a common piece size.','This is the least common multiple, which is larger than at least one roll.','A 1 cm piece works, but is not the greatest possible length.'];verify={kind:'gcf',a:a*b,b:a*c};break;
 case 'fractions':a=n(1,9);b=n(2,15);c=n(1,8);d=n(2,12);answer=fraction(a*d+c*b,b*d);stem=`What is ${a}/${b} + ${c}/${d}? Give an exact answer.`;steps=[`Use denominator ${b*d}: ${a}/${b} = ${a*d}/${b*d} and ${c}/${d} = ${c*b}/${b*d}.`,`Add numerators: (${a*d} + ${c*b})/${b*d} = ${answer}.`,`A common denominator preserves the size of both fractions.`];distractors=[fraction(a+c,b+d),fraction(a*c,b*d),fraction(a*d-c*b,b*d)];why=['Adding denominators changes the sizes of the fractional parts.','Multiplying fractions answers a different operation.','The question asks for the sum, not the difference.'];verify={kind:'fraction',num:a*d+c*b,den:b*d};break;
 case 'remainder':a=n(2,6);b=n(2,6);c=a*b*n(5,30);answer=c*(a-1)*(b-1)/(a*b);stem=`A tank holds ${c} liters. First 1/${a} of the water is used. Then 1/${b} of the remaining water is used. How many liters remain?`;steps=[`After the first use, ${c} × ${a-1}/${a} = ${c*(a-1)/a} liters remain.`,`The second fraction applies to the remainder: ${c*(a-1)/a} × ${b-1}/${b} = ${answer} liters.`,`Check by subtracting each actual amount used from ${c}.`];distractors=[c*(1-1/a-1/b),c/a/b,c*(a-1)/a];why=['The second fraction is of the remaining water, not the original tank.','This multiplies the used fractions instead of the remaining fractions.','This stops after the first use.'];verify={kind:'fraction',num:c*(a-1)*(b-1),den:a*b};break;
 case 'signed':a=n(-20,0);b=n(3,18);c=n(2,12);answer=a+b-c;stem=`At sunrise the temperature is ${a}°C. It rises ${b}°C and later falls ${c}°C. What is the final temperature in degrees Celsius?`;steps=[`A rise is positive: ${a} + ${b} = ${a+b}.`,`A fall is negative: ${a+b} − ${c} = ${answer}.`,`Check the direction of each change on a number line.`];distractors=[a+b+c,a-b-c,b-c];why=['The last change is a fall, so it must be subtracted.','The first change is a rise, so it must be added.','This omits the initial temperature.'];verify={kind:'order',a,b,c:1,d:c};break;
 case 'absolute':a=n(-35,-2);b=n(1,35);answer=b-a;stem=`What is the distance between ${a} and ${b} on a number line?`;steps=[`Distance is the absolute difference: |${b} − (${a})|.`,`Subtracting a negative adds its opposite: ${b} + ${-a} = ${answer}.`,`Distance is nonnegative and crosses zero here.`];distractors=[b+a,a-b,-a];why=['This subtracts the negative-side distance from the positive-side distance.','A negative value cannot represent a distance.','This counts only the distance from the left point to zero.'];verify={kind:'distance',a,b};break;
 case 'ratio':a=n(2,9);b=n(2,11);c=n(5,30);answer=b*c;stem=`The ratio of red beads to blue beads is ${a}:${b}. There are ${(a+b)*c} beads altogether. How many are blue?`;steps=[`The whole ratio contains ${a}+${b}=${a+b} equal parts.`,`One part is ${(a+b)*c} ÷ ${a+b} = ${c} beads.`,`Blue beads make up ${b} parts: ${b} × ${c} = ${answer}.`,`Check: red ${a*c} + blue ${answer} = ${(a+b)*c}.`];distractors=[a*c,(a+b)*c,c];why=['This finds the red beads.','This is the total number of beads.','This is one ratio part, not all the blue parts.'];verify={kind:'ratio',a,b,total:(a+b)*c};break;
 case 'rate':a=n(2,15);b=n(2,12);c=n(3,15);answer=fraction(a*c,b);stem=`A machine makes ${a*c} parts in ${b} hours at a constant rate. How many parts does it make per hour? Give an exact answer.`;steps=[`A unit rate compares the number of parts with one hour.`,`Divide output by hours: ${a*c} ÷ ${b} = ${answer} parts per hour.`,`Multiplying this rate by ${b} hours returns ${a*c} parts.`];distractors=[fraction(b,a*c),a*c*b,a*c];why=['This is hours per part, the reciprocal of the requested rate.','Multiplication produces parts-times-hours, not parts per hour.','This is the output during all the hours.'];verify={kind:'fraction',num:a*c,den:b};break;
 case 'speed':a=n(15,75);b=n(2,9);answer=a*b;stem=`A cyclist travels at a constant ${a} kilometers per hour for ${b} hours. How far does the cyclist travel, in kilometers?`;steps=[`Distance = rate × time.`,`The hours cancel in ${a} km/hour × ${b} hours = ${answer} km.`,`Check: ${answer} ÷ ${b} = ${a} km/hour.`];distractors=[fraction(a,b),a+b,b];why=['Dividing by time does not find distance.','Rate and time have different units and cannot be added.','This is the number of hours, not the distance.'];verify={kind:'product',factors:[a,b]};break;
 case 'scale':a=n(3,20);b=n(2,30);answer=a*b;stem=`On a map, 1 centimeter represents ${a} kilometers. Two towns are ${b} centimeters apart on the map. What is their actual distance, in kilometers?`;steps=[`Each map centimeter represents ${a} km.`,`Multiply the ${b} equal scale units: ${b} × ${a} = ${answer} km.`,`Check: ${answer} ÷ ${a} = ${b} map centimeters.`];distractors=[fraction(b,a),a+b,a];why=['Dividing uses the inverse scale.','Scale and map length are multiplied, not added.','This is the distance represented by only one centimeter.'];verify={kind:'product',factors:[a,b]};break;
 case 'percent':a=n(10,90)*10;b=[10,20,25,40,50][n(0,4)];c=[10,20,25,40,50][n(0,4)];answer=fraction(a*(100+b)*(100-c),10000);stem=`A $${a} item increases in price by ${b}%, then the new price decreases by ${c}%. What is the final price in dollars? Give an exact answer.`;steps=[`Increase multiplier: 1 + ${b}/100 = ${(100+b)/100}.`,`The increased price is ${a} × ${(100+b)/100} = ${a*(100+b)/100} dollars.`,`Apply the decrease to that new price: ${a*(100+b)/100} × ${(100-c)/100} = ${answer} dollars.`,`The two percentages use different reference prices.`];distractors=[fraction(a*(100+b-c),100),fraction(a*(100+b),100),fraction(a*(100-c),100)];why=['Subtracting the percentages treats both changes as percentages of the original price.','This applies the increase but omits the decrease.','This applies the decrease to the original price and omits the increase.'];verify={kind:'fraction',num:a*(100+b)*(100-c),den:10000};break;
 case 'original':a=n(10,150)*4;b=[10,20,25,40,50][n(0,4)];answer=a;stem=`After a ${b}% discount, an item costs $${a*(100-b)/100}. What was its original price in dollars?`;steps=[`The sale price is ${100-b}% of the original.`,`Let p be the original price: ${(100-b)/100}p = ${a*(100-b)/100}.`,`Divide by ${(100-b)/100}: p = ${answer}.`,`Check: ${a} − ${a*b/100} = ${a*(100-b)/100}.`];distractors=[a*(100-b)/100,a*(100-b)/100*(100+b)/100,a*b/100];why=['This is the already discounted price.','Increasing a sale price by the discount percentage does not undo the discount.','This is the discount amount, not the original price.'];verify={kind:'original',sale:a*(100-b),percent:b};break;
 case 'interest':a=n(5,100)*100;b=n(2,9);c=n(2,7);answer=a*b*c/100;stem=`A principal of $${a} earns simple interest at ${b}% per year for ${c} years. How much interest, in dollars, is earned?`;steps=[`Simple interest is I = P × r × t.`,`Write the rate as a decimal: ${b}% = ${b/100}.`,`I = ${a} × ${b/100} × ${c} = ${answer}.`,`This is interest alone; the final balance would also include the principal.`];distractors=[a+answer,a*b/100,a*b*c];why=['This gives the total balance, although the question asks for interest only.','This counts only one year of interest.','This uses a percent as a whole-number rate instead of dividing it by 100.'];verify={kind:'product',factors:[a,b/100,c]};break;
 case 'equation':a=n(2,15);b=n(-20,20);c=n(2,25);answer=c;stem=`Solve for x: ${a}x ${b<0?'−':'+'} ${Math.abs(b)} = ${a*c+b}.`;steps=[`Undo the ${b<0?'subtraction':'addition'}: ${a}x = ${a*c+b} − (${b}) = ${a*c}.`,`Divide both sides by ${a}: x = ${c}.`,`Check: ${a}(${c}) + (${b}) = ${a*c+b}.`];distractors=[fraction(a*c+2*b,a),a*c,fraction(a*c+b,a)];why=['This performs the constant operation again instead of undoing it.','This isolates ax but does not divide by the coefficient.','This divides before removing the constant.'];verify={kind:'equation',a,b,r:a*c+b};break;
 case 'distribute':a=n(2,12);b=n(2,15);c=n(2,20);answer=a*(b+c);stem=`If x = ${c}, what is the value of ${a}(x + ${b})?`;steps=[`Replace x with ${c}: ${a}(${c} + ${b}).`,`Evaluate the parentheses: ${c}+${b}=${c+b}.`,`Multiply: ${a} × ${c+b} = ${answer}.`,`Alternatively, ${a}×${c} + ${a}×${b} gives the same value.`];distractors=[a*c+b,a*b+c,a+c+b];why=['The coefficient must multiply both terms in parentheses.','The coefficient must also multiply x.','This treats multiplication as addition.'];verify={kind:'product',factors:[a,b+c]};break;
 case 'inequality':a=n(2,10);b=n(2,15);c=n(2,20);answer=c;stem=`What is the boundary value of x in the inequality −${a}x + ${b} < ${b-a*c}? The solution has the form x > ___.`;steps=[`Subtract ${b}: −${a}x < ${-a*c}.`,`Divide by −${a} and reverse the inequality: x > ${c}.`,`At x=${c}, the sides are equal; the strict inequality excludes this boundary.`];distractors=[-c,b-a*c,c+1];why=['The quotient of two negative values is positive.','This is the right side before isolating x.','The boundary is the equality value, not the next integer.'];verify={kind:'equation',a:-a,b,r:b-a*c};break;
 case 'angles':a=n(15,80);b=n(20,75);answer=180-a-b;stem=`Two interior angles of a triangle measure ${a}° and ${b}°. What is the third angle, in degrees?`;steps=[`The three interior angles sum to 180°.`,`Subtract the known angles: 180 − ${a} − ${b} = ${answer}°.`,`Check: ${a}+${b}+${answer}=180.`];distractors=[a+b,360-a-b,180-a];why=['This adds the two known angles instead of finding the missing one.','360° is the angle sum around a point, not inside a triangle.','This removes only one of the two known angles.'];verify={kind:'angles',a,b};break;
 case 'area':a=n(8,30);b=n(8,30);c=n(2,6);d=n(2,6);answer=a*b-c*d;stem=`A rectangular garden measures ${a} m by ${b} m. A ${c} m by ${d} m rectangular shed occupies part of the garden. How many square meters remain uncovered?`;steps=[`Whole garden area = ${a} × ${b} = ${a*b} m².`,`Shed area = ${c} × ${d} = ${c*d} m².`,`Uncovered area = ${a*b} − ${c*d} = ${answer} m².`,`Both subtracted quantities are areas measured in square meters.`];distractors=[a*b+c*d,a*b,2*(a+b)-2*(c+d)];why=['The shed occupies space, so its area is subtracted.','This ignores the shed.','This subtracts perimeters rather than areas.'];verify={kind:'area',a,b,c,d};break;
 case 'volume':a=n(3,20);b=n(3,18);c=n(3,15);answer=a*b*c;stem=`A rectangular box has inner dimensions ${a} cm, ${b} cm, and ${c} cm. What is its volume in cubic centimeters?`;steps=[`Volume = length × width × height.`,`V = ${a} × ${b} × ${c} = ${answer} cm³.`,`Each layer contains ${a*b} unit cubes and there are ${c} layers.`];distractors=[a*b,a+b+c,2*(a*b+a*c+b*c)];why=['This finds only the area of the base.','Adding dimensions does not measure occupied space.','This is surface area, not volume.'];verify={kind:'product',factors:[a,b,c]};break;
 case 'surface':a=n(2,20);b=n(2,15);c=n(2,15);answer=2*(a*b+a*c+b*c);stem=`A closed rectangular prism measures ${a} cm by ${b} cm by ${c} cm. What is its total surface area, in square centimeters?`;steps=[`Opposite faces form three equal pairs.`,`The face areas are ${a*b}, ${a*c}, and ${b*c} cm².`,`Total area = 2(${a*b}+${a*c}+${b*c}) = ${answer} cm².`,`All six faces are included because the prism is closed.`];distractors=[a*b*c,a*b+a*c+b*c,2*(a+b+c)];why=['This calculates volume in cubic centimeters.','This counts one face from each pair, only half the surface.','This adds edge lengths, which do not measure area.'];verify={kind:'surface',a,b,c};break;
 case 'average':a=n(10,60);b=n(10,60);c=n(10,60);d=n(10,60);answer=d;stem=`The mean of four numbers is ${(a+b+c+d)/4}. Three numbers are ${a}, ${b}, and ${c}. What is the fourth number?`;steps=[`Mean = total ÷ count, so total = ${(a+b+c+d)/4} × 4 = ${a+b+c+d}.`,`The three known numbers total ${a+b+c}.`,`Missing value = ${a+b+c+d} − ${a+b+c} = ${d}.`,`Check: (${a}+${b}+${c}+${d}) ÷ 4 = ${(a+b+c+d)/4}.`];distractors=[(a+b+c+d)/4,(a+b+c)/3,a+b+c+d];why=['The mean is not necessarily the missing value.','This is the mean of only the known numbers.','This is the total of all four numbers.'];verify={kind:'average',known:[a,b,c],mean:(a+b+c+d)/4};break;
 case 'probability':a=n(2,15);b=n(2,15);answer=fraction(a*(a-1),(a+b)*(a+b-1));stem=`A bag holds ${a} red and ${b} blue marbles. Two marbles are chosen at random without replacement. What is the probability that both are red?`;steps=[`First red probability = ${a}/${a+b}.`,`One red and one total marble are removed, so the second probability is ${a-1}/${a+b-1}.`,`Multiply: (${a}/${a+b}) × (${a-1}/${a+b-1}) = ${answer}.`,`The result lies between 0 and 1, as any probability must.`];distractors=[fraction(a*a,(a+b)*(a+b)),fraction(a,a+b),fraction(a*(a-1),(a+b)*(a+b))];why=['This assumes the first marble was replaced.','This gives the probability for only the first draw.','The total decreases by one for the second draw.'];verify={kind:'fraction',num:a*(a-1),den:(a+b)*(a+b-1)};break;
 case 'counting':a=n(2,8);b=n(2,8);answer=a*b;stem=`A lunch menu offers ${a} sandwiches and ${b} drinks. A meal includes exactly one sandwich and one drink. How many different meals are possible?`;steps=[`For each sandwich there are ${b} drink choices.`,`There are ${a} such groups, so ${a} × ${b} = ${answer} meals.`,`An organized table would contain ${a} rows and ${b} columns.`];distractors=[a+b,a,b];why=['Adding counts choices of one kind, not pairs of both kinds.','This counts only the sandwiches.','This counts only the drinks.'];verify={kind:'product',factors:[a,b]};break;
 case 'powers':a=n(2,5);b=n(2,4);c=n(1,3);answer=a**(b+c);stem=`What is the value of ${a}^${b} × ${a}^${c}?`;steps=[`Equal bases are retained and their exponents are added.`,`${a}^${b} × ${a}^${c} = ${a}^${b+c} = ${answer}.`,`This represents ${b+c} factors of ${a}.`];distractors=[a**(b*c),a**b+a**c,a*(b+c)];why=['Multiplying exponents is for a power raised to another power.','This adds powers instead of multiplying.','An exponent represents repeated multiplication, not a product with the exponent.'];verify={kind:'product',factors:[a**b,a**c]};break;
 case 'pythagoras':a=n(1,20);answer=5*a;stem=`A right triangle has legs ${3*a} cm and ${4*a} cm. What is the hypotenuse length, in centimeters?`;steps=[`The Pythagorean theorem gives c² = (${3*a})² + (${4*a})².`,`The sum is ${25*a*a}, so c = ${5*a}.`,`The hypotenuse is longer than either leg, as required.`];distractors=[7*a,a,25*a*a];why=['Adding the legs does not find the diagonal.','Subtracting the legs does not find the diagonal.','This is the square of the hypotenuse, not its length.'];verify={kind:'hypotenuse',a:3*a,b:4*a};break;
 case 'linear':a=n(2,12);b=n(1,a-1);c=n(2,25);d=n(-10,10);answer=c;stem=`Solve: ${a}x + ${d} = ${b}x + ${(a-b)*c+d}.`;steps=[`Subtract ${b}x from both sides: ${a-b}x + ${d} = ${(a-b)*c+d}.`,`Subtract ${d}: ${a-b}x = ${(a-b)*c}.`,`Divide by ${a-b}: x = ${c}.`,`Substitute ${c} in both original sides; both equal ${a*c+d}.`];distractors=[fraction((a-b)*c,a+b),fraction((a-b)*c+d,a-b),(a-b)*c];why=['The coefficients are subtracted when moving the variable term.','This does not subtract the constant.','This does not divide by the remaining coefficient.'];verify={kind:'equation',a:a-b,b:d,r:(a-b)*c+d};break;
 case 'slope':a=n(1,15);b=n(1,15);c=n(2,10);d=n(-15,15);answer=fraction(b,a);stem=`A line passes through (${d}, ${c}) and (${d+a}, ${c+b}). What is its slope?`;steps=[`Slope = change in y ÷ change in x.`,`The change in y is ${c+b} − ${c} = ${b}.`,`The change in x is ${d+a} − (${d}) = ${a}.`,`Slope = ${b}/${a} = ${answer}.`];distractors=[fraction(a,b),b,a];why=['This is run divided by rise, the reciprocal.','This uses only the rise.','This uses only the run.'];verify={kind:'fraction',num:b,den:a};break;
 default:throw new Error('No approved generator for this skill.');
 }
 let format=forceFormat||(random()<.22?'numeric':'single');const used=new Set([normalizeNumber(String(answer))]);const options:{id:string;text:string}[]=[{id:'correct',text:String(answer)}];const reasons:Record<string,string>={correct:'This value satisfies the calculation and the verification shown above.'};
 for(let k=0;k<distractors.length;k++){let t=String(distractors[k]);let canonical=normalizeNumber(t);if(canonical===null||used.has(canonical))continue;used.add(canonical);let id=`d${k}`;options.push({id,text:t});reasons[id]=why[k]}
 for(let k=1;options.length<4&&k<30;k++){let t=String(Number(answer)+k);if(!Number.isFinite(Number(t)))t=fraction(Number(verify.num||1)+k,Number(verify.den||1));let norm=normalizeNumber(t);if(norm!==null&&!used.has(norm)){used.add(norm);const id=`f${k}`;options.push({id,text:t});reasons[id]=`This value fails the relationship used in the solution. Recompute the final operation and check the result against the original quantities.`}}
 for(let i=options.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[options[i],options[j]]=[options[j],options[i]]}
 const topicInfo=mathTopics.find(t=>t.id===topic)!;
 return{id:`math:${topic}:${seed}:v1`,version:'1',blueprint:topic,subject:'Math',topic,domain:topicInfo.domain,grade:topicInfo.grade,difficulty,format,stem,options:format==='single'?options:undefined,key:format==='single'?'correct':String(answer),steps,why:reasons,takeaway:`Identify the reference quantity, write a mathematical relationship, and check ${topicInfo.title.toLowerCase()} against the original situation.`,verify,standard};
}
export function normalizeNumber(s:string):string|null{try{s=s.trim().replace(/−/g,'-').replace(/\s/g,'');if(s.length>80)return null;const parts=s.split('/');if(parts.length>2)return null;const rational=(v:string):[bigint,bigint]=>{if(!/^[+-]?\d+(\.\d+)?$/.test(v))throw Error();let [whole,decimal='']=v.split('.');if(decimal.length>12)throw Error();let sign=whole.startsWith('-')?-BigInt(1):BigInt(1);return[sign*BigInt(whole.replace(/^[+-]/,'')+decimal),BigInt(10)**BigInt(decimal.length)]};let [a,b]=rational(parts[0]);if(parts[1]){let [c,d]=rational(parts[1]);if(c===BigInt(0))return null;a*=d;b*=c}if(b<0){a=-a;b=-b}let x=a<0?-a:a,y=b;while(y){[x,y]=[y,x%y]}return `${a/x}/${b/x}`}catch{return null}}
export function isCorrect(item:Item,response:any){if(item.format==='numeric')return typeof response==='string'&&normalizeNumber(response)!==null&&normalizeNumber(response)===normalizeNumber(String(item.key));return response===item.key}
export function publicItem(item:Item){const {key,steps,why,takeaway,verify,evidence,blueprint,difficulty,...safe}=item;return {...safe,options:item.options?.map((option,index)=>({id:'option-'+index,text:option.text}))}}
