import ts from 'typescript';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync('.sites-runtime/qa',{recursive:true});
for(const name of ['math','ela']){let source=readFileSync('lib/content/'+name+'.ts','utf8').replace("'./math'","'./math.mjs'");writeFileSync('.sites-runtime/qa/'+name+'.mjs',ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText)}
const {mathTopics,mathItem,normalizeNumber,isCorrect}=await import('../.sites-runtime/qa/math.mjs');
let failures=[],report=[];
const number=v=>{let [a,b=1]=String(v).split('/').map(Number);return a/b};
for(const t of mathTopics){let stems=new Set(),signatures=new Set();for(let seed=0;seed<1000;seed++){try{const item=mathItem(t.id,seed);let v=item.verify,want;switch(v.kind){case 'order':want=v.a+v.b*v.c-v.d;break;case 'gcf':{const g=(a,b)=>b?g(b,a%b):a;want=g(v.a,v.b);break}case 'fraction':want=v.num/v.den;break;case 'distance':want=Math.abs(v.b-v.a);break;case 'ratio':want=v.total*v.b/(v.a+v.b);break;case 'product':want=v.factors.reduce((a,b)=>a*b,1);break;case 'original':want=v.sale/(100-v.percent);break;case 'equation':want=(v.r-v.b)/v.a;break;case 'angles':want=180-v.a-v.b;break;case 'area':want=v.a*v.b-v.c*v.d;break;case 'surface':want=2*(v.a*v.b+v.a*v.c+v.b*v.c);break;case 'average':want=v.mean*4-v.known.reduce((a,b)=>a+b,0);break;case 'hypotenuse':want=Math.hypot(v.a,v.b);break;default:throw Error('Missing independent verifier')}
let got=item.format==='numeric'?item.key:item.options.find(o=>o.id===item.key).text;assert.ok(Math.abs(number(got)-want)<1e-7,`Key ${got} != ${want}`);assert.ok(item.steps.length>=2);assert.ok(item.stem.length>10);if(item.format==='single'){assert.equal(item.options.length,4);assert.equal(new Set(item.options.map(o=>normalizeNumber(o.text))).size,4);assert.equal(item.options.filter(o=>isCorrect(item,o.id)).length,1);for(const o of item.options)assert.ok(item.why[o.id]?.length>10)}else assert.ok(isCorrect(item,String(got)));stems.add(item.stem);signatures.add(JSON.stringify(v));assert.equal(JSON.stringify(mathItem(t.id,seed)),JSON.stringify(item));}catch(e){failures.push({topic:t.id,seed,error:e.message})}}
report.push({blueprint:t.id,testedSeeds:1000,uniqueStemsInSample:stems.size,uniqueModelsInSample:signatures.size});}
assert.equal(normalizeNumber('6/8'),normalizeNumber('0.75'));assert.equal(normalizeNumber('1/0'),null);assert.equal(normalizeNumber('1;fetch(1)'),null);assert.equal(normalizeNumber('0.1'),normalizeNumber('1/10'));assert.equal(normalizeNumber('-2/4'),normalizeNumber('-0.5'));assert.equal(normalizeNumber('-.5'),null); // leading-zero rule: -.5 is intentionally invalid
const {authoredItems,reading}=await import('../.sites-runtime/qa/ela.mjs');
for(const item of authoredItems){assert.equal(item.options.length,4);assert.equal(item.options.filter(o=>o.id===item.key).length,1);assert.equal(new Set(item.options.map(o=>o.text)).size,4);for(const o of item.options)assert.ok(item.why[o.id]?.length>10);assert.ok(item.steps.length);if(item.passage)assert.equal(item.passage.paragraphs.join('\n'),reading.find(p=>p.id===item.setId).paragraphs.join('\n'))}
writeFileSync('tests/content-validation-report.json',JSON.stringify({generatedAt:new Date().toISOString(),blueprints:report,seedTests:27000,failures,authoredELA:authoredItems.length,passages:reading.length,editorialStatus:'ELA drafts; independent staff review required',countsNote:'Unique parameter variants in a sample are not authored question types or an exhaustively validated capacity.'},null,2));
if(failures.length){console.log(JSON.stringify(failures.slice(0,12),null,2));throw Error(`${failures.length} content validation failures`)}console.log(`Passed: 27,000 seeded math checks, ${authoredItems.length} ELA structural checks. Editorial review remains required.`);
