'use client';
import './content.css';
import {Lightbulb} from 'lucide-react';
import type {Question} from '@/lib/assessment';
import {DIFFICULTIES} from '@/lib/assessment';
import {findSubtopic} from '@/lib/curriculum';

export function QuestionRepresentation({q}:{q:Question}){
  return <>{q.table&&<figure className="question-table"><figcaption>{q.table.caption||'Use the information in this table.'}</figcaption><div className="table-wrap"><table><thead><tr>{q.table.headers.map((header,i)=><th key={i}>{header}</th>)}</tr></thead><tbody>{q.table.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div></figure>}{q.diagram&&<Diagram diagram={q.diagram}/>}</>;
}
function Diagram({diagram}:{diagram:NonNullable<Question['diagram']>}){
 const points=diagram.points||[],xs=points.map(point=>point.x),ys=points.map(point=>point.y),minX=Math.min(0,...xs)-3,maxX=Math.max(0,...xs)+3,minY=Math.min(0,...ys)-3,maxY=Math.max(0,...ys)+3;
 const x=(value:number)=>45+(value-minX)/(maxX-minX)*300,y=(value:number)=>235-(value-minY)/(maxY-minY)*190;
 const numberLine=points.length===1&&points[0].y===0;
 return <figure className="question-diagram">{points.length>0&&<svg role="img" aria-label={diagram.description} viewBox="0 0 400 280"><title>{diagram.description}</title><line x1="30" y1={y(0)} x2="360" y2={y(0)} stroke="currentColor" opacity=".35"/>{!numberLine&&<line x1={x(0)} y1="25" x2={x(0)} y2="250" stroke="currentColor" opacity=".35"/>}{diagram.segments?.map((segment,i)=>{const from=points.find(point=>point.label===segment.from),to=points.find(point=>point.label===segment.to);return from&&to?<line key={i} x1={x(from.x)} y1={y(from.y)} x2={x(to.x)} y2={y(to.y)} stroke="currentColor" strokeWidth="2"/>:null})}{points.map(point=><g key={point.label}><circle cx={x(point.x)} cy={y(point.y)} r="4" fill={/open circle/i.test(diagram.description)?'white':'currentColor'} stroke="currentColor"/><text x={x(point.x)+8} y={y(point.y)-10}>{point.label}</text><text x={x(point.x)} y={y(point.y)+20} textAnchor="middle">{numberLine?point.x:`(${point.x}, ${point.y})`}</text></g>)}{!numberLine&&<><text x="365" y={y(0)+5}>x</text><text x={x(0)+8} y="24">y</text></>}{diagram.labels?.map((label,i)=><text key={i} x={x(label.x)} y={y(label.y)}>{label.text}</text>)}</svg>}<figcaption>{diagram.description} Diagram may not be drawn to scale.</figcaption></figure>;
}
type ReviewQuestion=Question&{answer?:unknown;originalAnswer?:unknown;status?:string};
export function TutorExplanation({q,showPassage=false}:{q:ReviewQuestion;showPassage?:boolean}){
 const answer=q.answer??q.originalAnswer,index=Number(answer),selected=q.type==='grid'?String(answer??'Unanswered'):q.choices?.[index]??'Unanswered',correct=q.type==='grid'?String(q.correct):q.choices?.[Number(q.correct)];
 const steps=q.solutionSteps?.length?q.solutionSteps:[q.explanation];
 return <div className="explanation">{showPassage&&q.passage&&<details open><summary>Original passage · {q.passage.title}</summary><p className="review-passage">{q.passage.content}</p></details>}<QuestionRepresentation q={q}/><div className="answer-comparison"><div><span>Your answer</span><strong>{selected}</strong></div><div><span>Correct answer</span><strong>{correct}</strong></div></div><section><h4>HOW TO THINK ABOUT THIS QUESTION</h4><p>{q.howToThink||q.breakthrough}</p></section>{q.status==='incorrect'&&<section><h4>WHY YOUR ANSWER WAS WRONG</h4><p>{q.type==='grid'?`Your answer is ${selected}; the supported result is ${correct}. Follow the quantities and calculations below to locate where they differ. ${q.commonTrap}`:q.distractorReasons?.[index]||`${q.commonTrap} Your choice does not establish the relationship described below; the exact cause of your selection cannot be determined from the answer alone.`}</p></section>}<section><h4>{q.subject==='Math'?'STEP-BY-STEP SOLUTION':'EVIDENCE AND REASONING'}</h4>{q.subject==='Math'?<ol className="solution-steps">{steps.map((step,i)=><li key={i}>{step}</li>)}</ol>:<><p>{q.explanation}</p>{q.evidence&&<blockquote>“{q.evidence}”</blockquote>}{q.evidenceExplanation&&<p>{q.evidenceExplanation}</p>}</>}</section>{q.choices&&<section><h4>UNDERSTAND THE OTHER CHOICES</h4>{q.choices.map((choice,i)=><div className="option-explanation" key={i}><b>{'ABCD'[i]}. {choice}</b><p>{q.distractorReasons?.[i]||(i===q.correct?q.explanation:q.commonTrap)}</p></div>)}</section>}<section><h4>COMMON TRAP</h4><p>{q.commonTrap}</p></section><div className="breakthrough"><Lightbulb size={23}/><div><h4>BREAKTHROUGH</h4><p>{q.breakthrough}</p></div></div><p className="tiny">{findSubtopic(q.subtopic)?.label||q.skill} · {DIFFICULTIES[q.difficulty-1]}</p></div>;
}
