import {database,runtime} from './db';
import {cookie,digest,hashPassword,password,randomToken,same,username,verifyPassword} from './auth';
import {mathItem,mathTopics,isCorrect,publicItem,type Item,rng} from './content/math';
import {authoredItems as baseItems,reading,elaTopics,shuffled,passageItems,grammarItems} from './content/ela';
import checklist from './content/curriculum.json';
import {ability,band} from './adaptive';
import {validateDraft} from './content/author';
import {EXAM} from './exam';
import {summarizeAttempt,validateCalibration,type Calibration} from './scoring';
const now=()=>Date.now();const id=()=>crypto.randomUUID();
const clean=(x:any,max=200)=>{if(typeof x!=='string')throw Error('Please complete every required field.');return x.trim().slice(0,max)};
const json=(data:any,status=200,headers:any={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});
class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
const fail=(s:number,m:string):never=>{throw new HttpError(s,m)};
const safeUser=(u:any)=>({id:u.id,username:u.username,name:u.name,role:u.role,state:u.state,enrollment:u.enrollment,grade:u.grade,mustChange:!!u.must_change});
const topics=[...mathTopics,...elaTopics];
const defaults={center:'Queens Scholars Tutorial',phone:'718-913-7706',programs:[{title:'Grade 8 SHSAT preparation',grade:8,description:'Build core math and reading skills with teacher-guided practice and detailed mistake review.'},{title:'Grade 9 SHSAT preparation',grade:9,description:'Strengthen SHSAT skills and study the additional Grade 8 mathematics content for the Grade 9 exam.'}]};
export async function handler(req:Request,path:string[]){const db=database();const one=async(sql:string,...args:any[])=>db.prepare(sql).bind(...args).first<any>();const all=async(sql:string,...args:any[])=>((await db.prepare(sql).bind(...args).all<any>()).results||[]);const run=(sql:string,...args:any[])=>db.prepare(sql).bind(...args).run();const stmt=(sql:string,...args:any[])=>db.prepare(sql).bind(...args);const log=(actor:string,action:string,target:string)=>stmt('INSERT INTO audit (id,actor,action,target,created) VALUES (?,?,?,?,?)',id(),actor,action,target,now());
 try{
 const route=path.join('/');const method=req.method;let b:any={};
 if(method!=='GET'){
  const origin=req.headers.get('origin');const validOrigins=[new URL(req.url).origin,runtime().SITE_ORIGIN].filter(Boolean);
  if(!origin||!validOrigins.includes(origin))fail(403,'This request could not be verified. Please reload the page.');
  if(!req.headers.get('content-type')?.startsWith('application/json'))fail(415,'Send a JSON request.');
  const raw=await req.text();if(raw.length>600000)fail(413,'The request is too large.');try{b=JSON.parse(raw)}catch{fail(400,'Invalid request.')}if(!b||Array.isArray(b)||typeof b!=='object')fail(400,'Invalid request.');
 }
 const limit=async(key:string,max:number,ms:number)=>{let k=digest(key);await run('INSERT INTO limits (key,hits,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET hits=CASE WHEN expires<? THEN 1 ELSE hits+1 END, expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END',k,now()+ms,now(),now());const row=await one('SELECT hits FROM limits WHERE key=?',k);if(row.hits>max)fail(429,'Too many attempts. Please try again later.');};
 const phone=async()=>defaults.phone;
 if(route==='public'&&method==='GET'){const settings=await one('SELECT value FROM settings WHERE key=?','public');let config=settings?JSON.parse(settings.value):defaults;const programs=await all('SELECT title,description,grade,schedule FROM classes WHERE visible=1 AND state=?','active');return json({config,programs:programs.length?programs:config.programs,setupNeeded:!(await one('SELECT id FROM users WHERE role=?','admin'))})}
 if(route==='inquiry'&&method==='POST'){await limit('inquiry:'+req.headers.get('cf-connecting-ip'),5,3600000);if(b.website)fail(400,'Unable to save this request.');let name=clean(b.name,100),contact=clean(b.contact,100),p=clean(b.phone,40).replace(/\D/g,'');if(name.length<2||contact.length<2||p.length<10||p.length>15||![7,8,9].includes(Number(b.grade)))fail(400,'Enter the student name, grade, contact name, and a valid phone number.');let duplicate=await one('SELECT id FROM inquiries WHERE phone=? AND name=? AND created>?',p,name,now()-86400000);if(!duplicate)await run('INSERT INTO inquiries (id,name,grade,contact,phone,interest,message,created) VALUES (?,?,?,?,?,?,?,?)',id(),name,Number(b.grade),contact,p,clean(b.interest||'SHSAT preparation'),clean(b.message||'',1500),now());return json({saved:true,message:'Your enrollment request has been saved. Staff will contact you to discuss availability and provide login details after enrollment.'})}
 if(route==='setup'&&method==='POST'){await limit('setup:'+req.headers.get('cf-connecting-ip'),5,3600000);let secret=runtime().ADMIN_SETUP_TOKEN;if(!secret||typeof b.token!=='string'||!same(b.token,secret))fail(403,'Use your private administrator setup link.');if(await one('SELECT value FROM settings WHERE key=?','bootstrapped'))fail(409,'The first administrator has already been created.');let uid=id(),user=username(b.username),pass=password(b.password);if(b.confirm!==pass)fail(400,'The passwords do not match.');let hash=await hashPassword(pass),name=clean(b.name||'Administrator',100);await db.batch([stmt('INSERT INTO settings (key,value) VALUES (?,?)','bootstrapped',uid),stmt('INSERT INTO users (id,username,name,role,hash,must_change,created) VALUES (?,?,?,?,?,0,?)',uid,user,name,'admin',hash,now()),stmt('INSERT INTO settings (key,value) VALUES (?,?)','public',JSON.stringify(defaults)),log(uid,'First administrator created',uid)]);return json({created:true})}
 if(route==='login'&&method==='POST'){let user;try{user=username(b.username)}catch{user='invalid-username'}await limit('login-ip:'+req.headers.get('cf-connecting-ip'),25,900000);await limit('login-user:'+user,10,900000);let u=await one('SELECT * FROM users WHERE username=?',user);let p=typeof b.password==='string'&&b.password.length<=128?b.password:'';if(!u){await hashPassword(p||'not-a-valid-password');fail(401,'The username or password is incorrect.')}if(!(await verifyPassword(p,u.hash))||u.state!=='active')fail(401,'The username or password is incorrect, or access is inactive.');let token=randomToken();await run('INSERT INTO sessions (token,user_id,expires) VALUES (?,?,?)',digest(token),u.id,now()+86400000);return json({user:safeUser(u)},200,{'Set-Cookie':cookie(req,token)})}
 let token=req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith('qst_session='))?.slice(12);let u=token?await one('SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token=? AND s.expires>?',digest(token),now()):null;
 if(route==='session'&&method==='GET')return json({user:u&&u.state==='active'?safeUser(u):null});
 if(route==='logout'&&method==='POST'){if(token)await run('DELETE FROM sessions WHERE token=?',digest(token));return json({loggedOut:true},200,{'Set-Cookie':cookie(req,'',true)})}
 if(!u||u.state!=='active')fail(401,'Your session or account access is inactive. Log in again or contact Queens Scholars Tutorial at 718-913-7706.');
 const staff=()=>{if(!['admin','teacher'].includes(u.role))fail(403,'This action is available to authorized staff.')};const admin=()=>{if(u.role!=='admin')fail(403,'Administrator access is required.')};
 const ownClass=async(cid:string)=>{if(u.role==='admin')return !!await one('SELECT id FROM classes WHERE id=?',cid);return !!await one('SELECT m.id FROM memberships m JOIN classes c ON c.id=m.class_id WHERE m.class_id=? AND m.user_id=? AND m.kind=? AND m.active=1 AND c.state=?',cid,u.id,'teacher','active')};
 const ownStudent=async(uid:string)=>{if(u.role==='admin')return true;return !!await one('SELECT s.id FROM memberships s JOIN memberships t ON s.class_id=t.class_id JOIN classes c ON c.id=s.class_id WHERE s.user_id=? AND s.kind=? AND t.user_id=? AND t.kind=? AND s.active=1 AND t.active=1 AND c.state=?',uid,'student',u.id,'teacher','active')};
 const ownAttempt=async(a:any)=>u.role==='admin'||a.user_id===u.id||(u.role==='teacher'&&await ownStudent(a.user_id));
 if(route==='password'&&method==='POST'){if(!await verifyPassword(String(b.current||''),u.hash))fail(400,'The current password is incorrect.');let p=password(b.password);if(p!==b.confirm)fail(400,'The passwords do not match.');if(same(p,String(b.current)))fail(400,'Choose a different password.');let hash=await hashPassword(p),nt=randomToken();await db.batch([stmt('UPDATE users SET hash=?,must_change=0 WHERE id=?',hash,u.id),stmt('DELETE FROM sessions WHERE user_id=?',u.id),stmt('INSERT INTO sessions (token,user_id,expires) VALUES (?,?,?)',digest(nt),u.id,now()+86400000),log(u.id,'Password changed',u.id)]);return json({changed:true},200,{'Set-Cookie':cookie(req,nt)})}
 if(u.must_change)fail(403,'Change your initial password before using the portal.');
 if(u.role==='student'&&(u.enrollment!=='active'||!await one('SELECT m.id FROM memberships m JOIN classes c ON c.id=m.class_id WHERE m.user_id=? AND m.kind=? AND m.active=1 AND c.state=?',u.id,'student','active')))fail(403,'Your enrollment is inactive. Please contact your teacher or call 718-913-7706.');
 const customRows=await all('SELECT * FROM custom_content');const authoredItems:Item[]=[...baseItems,...customRows.map(r=>JSON.parse(r.item))];const passages=[...reading,...customRows.map(r=>JSON.parse(r.item)).filter(i=>i.passage).map(i=>i.passage)].filter((p,i,ps)=>ps.findIndex(v=>v.id===p.id)===i);const reviews=await all('SELECT * FROM content_reviews');const states=new Map<string,string>(reviews.map(r=>[r.id,r.state]));
 const mathAllowed=mathTopics.filter(t=>states.get('math:'+t.id)!=='quarantined');
 const eligible=authoredItems.filter(i=>i.subject==='ELA'&&states.get(i.id)==='published');const customMath=authoredItems.filter(i=>i.subject==='Math'&&states.get(i.id)==='published');
 const buildItems=(subject:string,topic:string,count:number,grade:number,seed:number):Item[]=>{let items:Item[]=[],random=rng(seed);if(subject==='ELA'){let pool=eligible.filter(i=>i.grade<=grade&&(topic==='mixed'||i.topic===topic));if(pool.length<count)fail(409,`Only ${pool.length} published ELA questions match this selection. Choose a smaller set or ask staff to review more content.`);if(topic==='mixed'){let ps=[...new Set(pool.filter(i=>i.setId).map(i=>i.setId))];for(const pid of ps){let set=pool.filter(i=>i.setId===pid);if(items.length+set.length<=count)items.push(...set)}let rest=pool.filter(i=>!items.some(v=>v.id===i.id));items.push(...rest.slice(0,count-items.length));}else items=pool.slice(0,count);return items.map((v,i)=>shuffled(v,seed+i));}
 let custom=customMath.filter(i=>i.grade<=grade&&(topic==='mixed'||i.topic===topic));items.push(...custom.slice(0,count).map((v,i)=>shuffled(v,seed+i)));let pool=mathAllowed.filter(t=>t.grade<=grade&&(topic==='mixed'||t.id===topic));if(!pool.length)fail(409,'This topic does not have published practice content.');for(let i=items.length;i<count;i++){const t=pool[i%pool.length];items.push(mathItem(t.id,(seed+i*7919)>>>0,2))}return items};
 const buildDiagnostic=(grade:number,seed:number,startSubject:string,pool:Item[]=eligible):Item[]=>{
  const approved=mathTopics.filter(t=>t.grade<=grade&&states.get('math:'+t.id)==='published');
  if(approved.length!==mathTopics.filter(t=>t.grade<=grade).length)fail(409,'Full-length rehearsal needs staff scope review of every math blueprint in this grade track.');
  const sets=passages.map(p=>pool.filter(i=>i.grade<=grade&&i.setId===p.id)).filter(set=>set.length===5);
  const singles=pool.filter(i=>i.grade<=grade&&!i.setId);
  if(sets.length<8||singles.length<10)fail(409,'Not enough reviewed, unexposed ELA content for a 50-question subject. Publish more content or use a mini diagnostic.');
  const ela=sets.slice(0,8).flat().concat(singles.slice(0,10)).map((item,k)=>shuffled(item,seed+k));
  const first=approved.find(t=>band(t.id)===2)||approved[0];
  const math=Array.from({length:50},(_,k)=>{const topic=k===0?first:approved[k%approved.length];return mathItem(topic.id,(seed+k*7919)>>>0,band(topic.id));});
  return startSubject==='ELA'?[...ela,...math]:[...math,...ela];
 };
 const score=(a:any)=>a.score_json?JSON.parse(a.score_json):summarizeAttempt(a);
 const currentCalibration=async(grade:number):Promise<Calibration|null>=>{const row=await one('SELECT payload FROM calibrations WHERE grade=? ORDER BY created DESC LIMIT 1',grade);return row?JSON.parse(row.payload):null};
 const saveSummary=async(a:any)=>{if(a.score_json)return;const viewed=await all('SELECT item_id FROM exposures WHERE user_id=?',a.user_id);const viewedIds=new Set(viewed.map(v=>v.item_id));const previous=await all('SELECT items FROM attempts WHERE user_id=? AND id!=?',a.user_id,a.id);for(const past of previous)for(const item of JSON.parse(past.items))viewedIds.add(item.id);const exposure=JSON.parse(a.items).some((i:Item)=>viewedIds.has(i.id));const summary=summarizeAttempt(a,await currentCalibration(a.grade),exposure);await run('UPDATE attempts SET score_json=? WHERE id=? AND score_json IS NULL',JSON.stringify(summary),a.id);a.score_json=JSON.stringify(summary)};
 const released=async(a:any)=>{if(a.state==='in-progress')return false;if(u.role!=='student'||!a.assignment_id||a.released)return true;let assignment=await one('SELECT a.feedback,r.due FROM assignments a JOIN recipients r ON r.assignment_id=a.id WHERE a.id=? AND r.user_id=?',a.assignment_id,a.user_id);return assignment?.feedback==='submission'||(assignment?.feedback==='due'&&assignment.due&&assignment.due<now())};
 const finish=async(a:any,status='submitted')=>{if(a.state!=='in-progress')return;let items:Item[]=JSON.parse(a.items),answers=JSON.parse(a.answers);const statements=[stmt('UPDATE attempts SET state=?,finished=?,revision=revision+1 WHERE id=? AND state=?',status,now(),a.id,'in-progress')];items.forEach((it,i)=>{if(answers[i]!==undefined&&!isCorrect(it,answers[i]))statements.push(stmt('INSERT OR IGNORE INTO mistakes (id,attempt_id,user_id,item_index,review_at) VALUES (?,?,?,?,?)',id(),a.id,a.user_id,i,now()+86400000))});await db.batch(statements);a.state=status;a.finished=now();await saveSummary(a);};
 const serialize=async(a:any)=>{if(a.state==='in-progress'&&a.deadline&&a.deadline<=now())await finish(a,'expired');const items:Item[]=JSON.parse(a.items),answers=JSON.parse(a.answers);let unlocked:number[]=[];if(a.state==='in-progress'){let current=items[a.cursor];if(current?.setId){items.forEach((v,i)=>{if(v.setId===current.setId&&v.subject===current.subject)unlocked.push(i)})}else if(current)unlocked=[a.cursor]};let show=await released(a);const displayedAnswers=show?answers:Object.fromEntries(Object.entries(answers).map(([index,response])=>{const item=items[Number(index)];return [index,item?.format==='single'?'option-'+item.options!.findIndex(option=>option.id===response):response]}));return{id:a.id,userId:a.user_id,assignmentId:a.assignment_id,title:a.title,mode:a.mode,grade:a.grade,state:a.state,cursor:a.cursor,revision:a.revision,started:a.started,deadline:a.deadline,serverTime:now(),finished:a.finished,answers:displayedAnswers,notes:JSON.parse(a.notes),conditions:JSON.parse(a.conditions||'{}'),unlocked,items:show?items.map(({verify,...i})=>i):items.map((i,index)=>unlocked.includes(index)?publicItem(i):{id:i.id,subject:i.subject,topic:i.topic,setId:i.setId}),summary:show?score(a):null,feedback:show?a.feedback:'',override:show?a.override:null,feedbackReleased:show};};
 if(route==='learning-plan'&&(method==='GET'||method==='POST')){
  const key='learning-plan:'+u.id,defaults={minutes:30,focus:'balanced',days:[1,2,3,4,5]};
  if(method==='GET'){const row=await one('SELECT value FROM settings WHERE key=?',key);return json({plan:row?JSON.parse(row.value):defaults})}
  if(![15,30,45,60].includes(Number(b.minutes))||!['balanced','Math','ELA'].includes(b.focus)||!Array.isArray(b.days)||b.days.length<1||b.days.length>7||b.days.some((v:any)=>!Number.isInteger(v)||v<0||v>6))fail(400,'Choose a 15–60 minute plan, a focus, and at least one study day.');
  const plan={minutes:Number(b.minutes),focus:b.focus,days:[...new Set(b.days)].sort()};
  await run('INSERT INTO settings (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',key,JSON.stringify(plan));return json({saved:true,plan});
 }
 if(route==='dashboard'&&method==='GET'){
 let classes=await all(u.role==='admin'?'SELECT * FROM classes ORDER BY created DESC':'SELECT c.* FROM classes c JOIN memberships m ON m.class_id=c.id WHERE m.user_id=? AND m.active=1 AND c.state=\'active\' ORDER BY c.created DESC',...(u.role==='admin'?[]:[u.id]));let people=u.role==='admin'?await all('SELECT id,username,name,role,state,enrollment,grade,must_change,revoked_by FROM users ORDER BY created DESC'):u.role==='teacher'?await all('SELECT DISTINCT u.id,u.username,u.name,u.role,u.state,u.enrollment,u.grade,u.must_change,u.revoked_by FROM users u JOIN memberships s ON s.user_id=u.id JOIN memberships t ON t.class_id=s.class_id JOIN classes c ON c.id=t.class_id WHERE t.user_id=? AND t.kind=\'teacher\' AND t.active=1 AND s.active=1 AND s.kind=\'student\' AND c.state=\'active\'',u.id):[];
 let members=classes.length?await all(`SELECT m.id,m.class_id,m.user_id,m.kind,m.active,u.name FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.class_id IN (${classes.map(()=>'?').join(',')}) AND m.active=1`,...classes.map(c=>c.id)):[];
 if(u.role==='student')members=members.filter(m=>m.user_id===u.id||m.kind==='teacher');
 let assignments=u.role==='admin'?await all('SELECT a.*,c.title class_title FROM assignments a JOIN classes c ON c.id=a.class_id ORDER BY a.created DESC'):u.role==='teacher'?await all('SELECT DISTINCT a.*,c.title class_title FROM assignments a JOIN classes c ON c.id=a.class_id JOIN memberships m ON m.class_id=a.class_id WHERE m.user_id=? AND m.kind=\'teacher\' AND m.active=1 AND c.state=\'active\' ORDER BY a.created DESC',u.id):await all('SELECT a.*,c.title class_title FROM assignments a JOIN recipients r ON r.assignment_id=a.id JOIN classes c ON c.id=a.class_id WHERE r.user_id=? AND a.state=\'published\' AND (a.published IS NULL OR a.published<=?) ORDER BY a.created DESC',u.id,now());
 assignments=assignments.map(({items,recipient_selection,...a})=>u.role==='student'?a:{...a,recipient_selection});
 let attempts=u.role==='admin'?await all("SELECT a.*,u.name student_name FROM attempts a JOIN users u ON u.id=a.user_id WHERE u.role='student' ORDER BY a.started DESC LIMIT 200"):u.role==='teacher'?await all('SELECT DISTINCT a.*,u.name student_name FROM attempts a JOIN users u ON u.id=a.user_id JOIN memberships s ON s.user_id=a.user_id JOIN memberships t ON t.class_id=s.class_id JOIN classes c ON c.id=t.class_id WHERE t.user_id=? AND t.kind=\'teacher\' AND t.active=1 AND s.active=1 AND s.kind=\'student\' AND c.state=\'active\' ORDER BY a.started DESC LIMIT 200',u.id):await all('SELECT * FROM attempts WHERE user_id=? ORDER BY started DESC LIMIT 100',u.id);
 let attemptsSafe=[];for(let a of attempts){if(a.state==='in-progress'&&a.deadline&&a.deadline<=now())await finish(a,'expired');let show=await released(a);attemptsSafe.push({id:a.id,title:a.title,userId:a.user_id,studentName:a.student_name,assignmentId:a.assignment_id,mode:a.mode,state:a.state,started:a.started,finished:a.finished,summary:show?score(a):null})}
 const requests=u.role==='admin'?await all('SELECT * FROM inquiries ORDER BY created DESC LIMIT 200'):[];const events=u.role==='admin'?await all('SELECT a.*,u.name actor_name FROM audit a LEFT JOIN users u ON u.id=a.actor ORDER BY a.created DESC LIMIT 30'):[];const mistakes=u.role==='student'?await all('SELECT * FROM mistakes WHERE user_id=? ORDER BY review_at',u.id):[];const announcements=classes.length?await all(`SELECT a.*,c.title class_title FROM announcements a JOIN classes c ON c.id=a.class_id WHERE a.class_id IN (${classes.map(()=>'?').join(',')}) ORDER BY a.created DESC LIMIT 30`,...classes.map(c=>c.id)):[];
 const myRows=await all('SELECT * FROM attempts WHERE user_id=? ORDER BY started DESC LIMIT 100',u.id);let myAttempts=[];for(const a of myRows){if(a.state==='in-progress'&&a.deadline&&a.deadline<=now())await finish(a,'expired');const show=await released(a);myAttempts.push({id:a.id,title:a.title,userId:a.user_id,assignmentId:a.assignment_id,mode:a.mode,state:a.state,started:a.started,finished:a.finished,summary:show?score(a):null})}const myMistakes=await all('SELECT * FROM mistakes WHERE user_id=? ORDER BY review_at',u.id);
 const config=await one('SELECT value FROM settings WHERE key=?','public');return json({myAttempts,myMistakes,user:safeUser(u),classes,people,members,assignments,attempts:attemptsSafe,requests,events,mistakes,announcements,config:config?JSON.parse(config.value):defaults,topics:topics.map(t=>({...t,publishedCount:t.subject==='ELA'?eligible.filter(i=>i.topic===t.id).length:states.get('math:'+t.id)==='quarantined'?0:null})),checklist,coverage:{mathBlueprints:mathAllowed.length,authoredELA:authoredItems.filter(i=>i.subject==='ELA').length,publishedELA:eligible.length,passages:passages.length,publishedPassages:passages.filter(p=>{const set=authoredItems.filter(i=>i.setId===p.id);return set.length===5&&set.every(i=>states.get(i.id)==='published')}).length,passageTarget:250,elaTarget:2000,diagnosticReady:eligible.length>=50&&passages.filter(p=>{const set=authoredItems.filter(i=>i.setId===p.id);return set.length===5&&set.every(i=>states.get(i.id)==='published')}).length>=8&&mathTopics.filter(t=>t.grade<=Math.max(8,u.grade)).every(t=>states.get('math:'+t.id)==='published'),calibration:'Uncalibrated',standardAudit:'Pending'},reviews});
 }
 if(route==='learning-track'&&method==='POST'){staff();const grade=Number(b.grade);if(![8,9].includes(grade))fail(400,'Choose a Grade 8 or Grade 9 track.');await db.batch([stmt('UPDATE users SET grade=? WHERE id=?',grade,u.id),log(u.id,'Personal study track updated',String(grade))]);return json({saved:true})}
 if(route==='revoke-access'&&method==='POST'){
  staff();const target=await one('SELECT * FROM users WHERE id=?',clean(b.id));if(!target||target.role==='admin')fail(403,'Only teacher or student accounts can be revoked here.');
  if(u.role==='teacher'&&(target.role!=='student'||!await ownStudent(target.id)))fail(403,'Only currently assigned student accounts are in your scope.');
  if(target.state==='revoked')return json({saved:true,state:'revoked'});
  if(u.role==='teacher'&&target.state!=='active')fail(403,'An administrator must manage an already inactive account.');
  const reason=clean(b.reason||'',1000),time=now();
  const result=await db.batch([stmt('UPDATE users SET state=\'revoked\',revoked_by=?,revoked_at=?,revoke_reason=? WHERE id=? AND state=?',u.id,time,reason,target.id,target.state),stmt('DELETE FROM sessions WHERE user_id=?',target.id),stmt('UPDATE attempts SET state=\'interrupted-revocation\',finished=?,revision=revision+1 WHERE user_id=? AND state=\'in-progress\'',time,target.id),log(u.id,'Access revoked ('+target.state+' → revoked)'+(reason?': '+reason:''),target.id)]);
  if(!result[0].meta.changes)fail(409,'The account changed in another session. Reload before continuing.');
  return json({saved:true,state:'revoked'});
 }
 if(route==='restore-access'&&method==='POST'){
  staff();const target=await one('SELECT * FROM users WHERE id=?',clean(b.id));if(!target||target.role==='admin'||target.state!=='revoked')fail(409,'Choose an account whose access is revoked.');
  if(u.role==='teacher'&&(target.role!=='student'||target.revoked_by!==u.id||target.enrollment!=='active'||!await ownStudent(target.id)))fail(403,'You may restore only your own revocation for a currently assigned student with active enrollment.');
  const result=await db.batch([stmt('UPDATE users SET state=\'active\',revoked_by=NULL,revoked_at=NULL,revoke_reason=NULL WHERE id=? AND state=\'revoked\' AND revoked_by=?',target.id,target.revoked_by),stmt('DELETE FROM sessions WHERE user_id=?',target.id),log(u.id,'Access restored (revoked → active); fresh login required',target.id)]);
  if(!result[0].meta.changes)fail(409,'The revocation changed in another session. Reload before restoring.');return json({saved:true,state:'active'});
 }
 if(route==='calibrations'&&method==='GET'){staff();const rows=await all('SELECT * FROM calibrations ORDER BY created DESC');return json({exam:EXAM,versions:rows.map(({payload,...row})=>({...row,mapping:JSON.parse(payload)})),canImport:u.role==='admin'})}
 if(route==='calibration-import'&&method==='POST'){admin();if(b.confirmReviewed!==true||clean(b.notes||'',4000).length<40)fail(400,'Confirm independent validation review and record its evidence before approving a mapping.');const mapping=validateCalibration(b.mapping);await db.batch([stmt('INSERT INTO calibrations (id,grade,payload,notes,actor,created) VALUES (?,?,?,?,?,?)',mapping.version,mapping.grade,JSON.stringify(mapping),clean(b.notes,4000),u.id,now()),log(u.id,'Score calibration approved; historical snapshots preserved',mapping.version)]);return json({saved:true,version:mapping.version})}
 if(path[0]==='assignment-preview'&&path[1]&&method==='GET'){staff();const a=await one('SELECT * FROM assignments WHERE id=?',path[1]);if(!a||!await ownClass(a.class_id))fail(403,'Assignment access denied.');const items:Item[]=JSON.parse(a.items);await db.batch(items.map(it=>stmt('INSERT INTO exposures (id,user_id,item_id,source,created) VALUES (?,?,?,?,?)',id(),u.id,it.id,'assignment-preview',now())));return json({assignment:{...a,items},preview:true,message:'Staff preview does not create a submission or count toward personal progress.'})}
 if(route==='users'&&method==='POST'){staff();if(b.role==='admin')fail(403,'Administrator provisioning is private; this form creates only teachers and students.');if(b.role&&!['student','teacher'].includes(b.role))fail(400,'Choose a student or teacher role.');let role=b.role==='teacher'?'teacher':'student';if(b.inquiryId&&role!=='student')fail(400,'Enrollment requests must create student accounts.');if(u.role!=='admin'&&role!=='student')fail(403,'Teachers cannot create staff accounts.');let cid=clean(b.classId||'');if((role==='student'||u.role==='teacher')&&(!cid||!await ownClass(cid)))fail(403,'Choose one of your authorized classes.');if(cid&&!await ownClass(cid))fail(403,'Class access denied.');let user=username(b.username),p=password(b.password),name=clean(b.name,100),grade=Number(b.grade);if(!name||![7,8,9].includes(grade))fail(400,'Enter a name and grade.');if(b.confirm!==p)fail(400,'The passwords do not match.');if(await one('SELECT id FROM users WHERE username=?',user))fail(409,'This username is already in use.');const uid=id(),hash=await hashPassword(p);const queries=[stmt('INSERT INTO users (id,username,name,role,grade,hash,created,source_inquiry) VALUES (?,?,?,?,?,?,?,?)',uid,user,name,role,grade,hash,now(),b.inquiryId?clean(b.inquiryId):null),log(u.id,role+' account created',uid)];if(cid)queries.push(stmt('INSERT INTO memberships (id,class_id,user_id,kind) VALUES (?,?,?,?)',id(),cid,uid,role));if(b.inquiryId){admin();let request=await one('SELECT * FROM inquiries WHERE id=?',clean(b.inquiryId));if(!request||request.user_id)fail(409,'This request has already been converted or is unavailable.');queries.push(stmt('UPDATE inquiries SET status=\'approved\',user_id=? WHERE id=? AND user_id IS NULL',uid,request.id))};await db.batch(queries);return json({created:true,user:{id:uid,username:user,name,role}})}
 if(route==='user-update'&&method==='POST'){staff();let target=await one('SELECT * FROM users WHERE id=?',clean(b.id));if(!target||target.role==='admin')fail(403,'This account cannot be managed through this form.');if(u.role==='teacher'&&(target.role!=='student'||!await ownStudent(target.id)))fail(403,'Student access denied.');let queries=[];if(b.password){let p=password(b.password);if(p!==b.confirm)fail(400,'The passwords do not match.');queries.push(stmt('UPDATE users SET hash=?,must_change=1 WHERE id=?',await hashPassword(p),target.id),stmt('DELETE FROM sessions WHERE user_id=?',target.id),log(u.id,'Password reset',target.id));}else{if(target.state==='revoked'&&b.state&&b.state!=='revoked')fail(409,'Use Restore access to reactivate a revoked account.');let name=clean(b.name||target.name,100),user=username(b.username||target.username);if(u.role==='teacher'&&user!==target.username)fail(403,'Only an administrator can change a username.');let state=u.role==='admin'?['active','suspended','archived'].includes(b.state)?b.state:target.state:target.state;let enrollment=u.role==='admin'?['active','paused','ended','archived'].includes(b.enrollment)?b.enrollment:target.enrollment:target.enrollment;queries.push(stmt('UPDATE users SET name=?,username=?,state=?,enrollment=? WHERE id=?',name,user,state,enrollment,target.id),log(u.id,'Account or enrollment updated',target.id));if(state!=='active'||enrollment!=='active')queries.push(stmt('DELETE FROM sessions WHERE user_id=?',target.id));}await db.batch(queries);return json({saved:true})}
 if(route==='classes'&&method==='POST'){admin();let cid=b.id?clean(b.id):id();if(b.id&&!await ownClass(cid))fail(404,'Class not found.');let title=clean(b.title,100),description=clean(b.description,1200),grade=Number(b.grade);if(title.length<2||![8,9].includes(grade))fail(400,'Enter a class title and grade track.');await db.batch([stmt('INSERT INTO classes (id,title,description,grade,schedule,state,visible,created) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,description=excluded.description,grade=excluded.grade,schedule=excluded.schedule,state=excluded.state,visible=excluded.visible',cid,title,description,grade,clean(b.schedule||'',200),b.state==='archived'?'archived':'active',b.visible?1:0,now()),log(u.id,'Class saved',cid)]);return json({saved:true,id:cid})}
 if(route==='membership'&&method==='POST'){staff();let cid=clean(b.classId),uid=clean(b.userId);if(!await ownClass(cid))fail(403,'Class access denied.');let target=await one('SELECT id,role FROM users WHERE id=?',uid);if(!target||!['teacher','student'].includes(target.role))fail(400,'Choose a teacher or student.');if(u.role==='teacher'&&(target.role!=='student'||!await ownStudent(uid)))fail(403,'Only an administrator can attach an unrelated account.');await db.batch([stmt('INSERT INTO memberships (id,class_id,user_id,kind,active) VALUES (?,?,?,?,?) ON CONFLICT(class_id,user_id) DO UPDATE SET active=excluded.active',id(),cid,uid,target.role,b.active===false?0:1),log(u.id,b.active===false?'Class membership removed':'Class membership added',uid)]);return json({saved:true})}
 if(route==='inquiry-update'&&method==='POST'){admin();if(!['new','contacted','approved','declined'].includes(b.status))fail(400,'Invalid request status.');await db.batch([stmt('UPDATE inquiries SET status=?,notes=? WHERE id=?',b.status,clean(b.notes||'',2000),clean(b.id)),log(u.id,'Enrollment inquiry updated',b.id)]);return json({saved:true})}
 if(route==='settings'&&method==='POST'){admin();let old=await one('SELECT value FROM settings WHERE key=?','public');let config=old?JSON.parse(old.value):defaults;config.programs=Array.isArray(b.programs)?b.programs.slice(0,10).map((p:any)=>({title:clean(p.title,100),description:clean(p.description,1200),grade:Number(p.grade)===9?9:8})):config.programs;await db.batch([stmt('UPDATE settings SET value=? WHERE key=?',JSON.stringify(config),'public'),log(u.id,'Public program information updated','public')]);return json({saved:true})}
 if(route==='announcement'&&method==='POST'){staff();let cid=clean(b.classId);if(!await ownClass(cid))fail(403,'Class access denied.');await run('INSERT INTO announcements (id,class_id,actor,message,created) VALUES (?,?,?,?,?)',id(),cid,u.id,clean(b.message,2000),now());return json({saved:true})}
 if(route==='assignments'&&method==='POST'){staff();let cid=clean(b.classId);if(!await ownClass(cid))fail(403,'Class access denied.');let cls=await one('SELECT * FROM classes WHERE id=?',cid);let count=Math.min(50,Math.max(1,Number(b.count)||10));let subject=b.subject==='ELA'?'ELA':'Math',topic=clean(b.topic||'mixed');let mode=['practice','quiz','homework','classwork','lesson','diagnostic'].includes(b.mode)?b.mode:'homework';const assignmentSeed=Math.floor(Math.random()*1e9);if(clean(b.title||'',120).length<2)fail(400,'Give the assignment a custom title.');let uid=id(),items=mode==='diagnostic'?buildDiagnostic(cls.grade,assignmentSeed,b.startSubject):buildItems(subject,topic,count,cls.grade,assignmentSeed),due=b.due?Date.parse(b.due):null;if(due!==null&&(!Number.isFinite(due)||due<now()))fail(400,'Choose a future due date.');let publish=b.publish!==false;const publication=b.publishAt?Date.parse(b.publishAt):now();if(!Number.isFinite(publication)||publication<now()-5000)fail(400,'Choose a current or future publication time.');const roster=await all('SELECT user_id FROM memberships WHERE class_id=? AND kind=\'student\' AND active=1',cid);let chosen=Array.isArray(b.studentIds)&&b.studentIds.length?roster.filter(r=>b.studentIds.includes(r.user_id)):roster;if(!chosen.length&&publish)fail(400,'Add students to this class before publishing work.');let queries=[stmt('INSERT INTO assignments (id,creator,class_id,title,instructions,mode,subject,topic,grade,count,items,recipient_selection,state,due,published,attempt_limit,minutes,feedback,created) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',uid,u.id,cid,clean(b.title,120),clean(b.instructions||'',2000),mode,subject,topic,cls.grade,items.length,JSON.stringify(items),JSON.stringify(Array.isArray(b.studentIds)?b.studentIds:[]),publish?'published':'draft',due,publish?publication:null,Math.min(5,Math.max(1,Number(b.attemptLimit)||1)),mode==='diagnostic'?EXAM.standardMinutes:Math.min(180,Math.max(0,Number(b.minutes)||0)),['submission','due','manual'].includes(b.feedback)?b.feedback:'submission',now()),log(u.id,publish?'Assignment published':'Assignment draft saved',uid)];if(publish)chosen.forEach(r=>queries.push(stmt('INSERT INTO recipients (id,assignment_id,user_id,due) VALUES (?,?,?,?)',id(),uid,r.user_id,due)));await db.batch(queries);return json({saved:true,id:uid})}
 if(route==='assignment-publish'&&method==='POST'){staff();let a=await one('SELECT * FROM assignments WHERE id=?',clean(b.id));if(!a||!await ownClass(a.class_id))fail(403,'Assignment access denied.');if(a.state!=='draft')fail(409,'This assignment is already published.');let roster=await all('SELECT user_id FROM memberships WHERE class_id=? AND kind=\'student\' AND active=1',a.class_id);const selected=JSON.parse(a.recipient_selection||'[]');if(selected.length)roster=roster.filter(r=>selected.includes(r.user_id));if(!roster.length)fail(400,'Add authorized recipients before publishing.');await db.batch([stmt('UPDATE assignments SET state=\'published\',published=? WHERE id=? AND state=\'draft\'',now(),a.id),...roster.map(r=>stmt('INSERT OR IGNORE INTO recipients (id,assignment_id,user_id,due) VALUES (?,?,?,?)',id(),a.id,r.user_id,a.due)),log(u.id,'Assignment published',a.id)]);return json({saved:true})}
 if(route==='feedback'&&method==='POST'){staff();let a=await one('SELECT * FROM attempts WHERE id=?',clean(b.id));if(!a||!await ownAttempt(a)||a.state==='in-progress')fail(403,'Submission access denied.');let override=b.override===''||b.override===undefined?null:Number(b.override);if(override!==null&&(!Number.isInteger(override)||override<0||override>JSON.parse(a.items).length))fail(400,'The corrected count must be within the assignment length.');if(override!==null&&clean(b.reason||'',300).length<5)fail(400,'Give a reason for the grade correction.');await db.batch([stmt('UPDATE attempts SET feedback=?,released=?,override=? WHERE id=?',clean(b.feedback||'',3000),b.release?1:0,override,a.id),log(u.id,override!==null?'Grade correction: '+clean(b.reason,300):'Feedback updated',a.id)]);return json({saved:true})}
 if(route==='extension'&&method==='POST'){staff();let assignment=await one('SELECT * FROM assignments WHERE id=?',clean(b.assignmentId));if(!assignment||!await ownClass(assignment.class_id)||!await ownStudent(clean(b.userId)))fail(403,'Recipient access denied.');let due=Date.parse(b.due);if(!Number.isFinite(due)||due<now())fail(400,'Choose a future deadline.');await db.batch([stmt('UPDATE recipients SET due=? WHERE assignment_id=? AND user_id=?',due,assignment.id,b.userId),log(u.id,'Individual due date extended',b.userId)]);return json({saved:true})}
 if(route==='approve-retry'&&method==='POST'){staff();const assignment=await one('SELECT * FROM assignments WHERE id=?',clean(b.assignmentId));if(!assignment||!await ownClass(assignment.class_id)||!await ownStudent(clean(b.userId)))fail(403,'Recipient access denied.');const recipient=await one('SELECT * FROM recipients WHERE assignment_id=? AND user_id=?',assignment.id,b.userId);if(!recipient)fail(404,'Recipient not found.');const count=await one('SELECT COUNT(*) total FROM attempts WHERE assignment_id=? AND user_id=?',assignment.id,b.userId);const limit=Math.max(count.total+1,(recipient.attempt_limit??assignment.attempt_limit)+1);if(limit>10)fail(409,'The maximum approved attempt count is 10.');await db.batch([stmt('UPDATE recipients SET attempt_limit=? WHERE id=?',limit,recipient.id),log(u.id,'Individual retry approved',b.userId)]);return json({saved:true,attemptLimit:limit})}
 if(route==='content'&&method==='GET'){staff();const viewed=u.role==='admin'?[...authoredItems,...mathTopics.map(t=>mathItem(t.id,1042))]:customRows.filter(r=>r.owner===u.id).map(r=>JSON.parse(r.item));if(viewed.length)await db.batch(viewed.map(it=>stmt('INSERT INTO exposures (id,user_id,item_id,source,created) VALUES (?,?,?,?,?)',id(),u.id,it.id,'content-review',now())));return json({items:u.role==='admin'?authoredItems:customRows.filter(r=>r.owner===u.id).map(r=>JSON.parse(r.item)),blueprints:(u.role==='admin'?mathTopics:[]).map(t=>({...t,sample:mathItem(t.id,1042)})),reviews:u.role==='admin'?reviews:reviews.filter(r=>customRows.some(c=>c.id===r.id&&c.owner===u.id)),reports:u.role==='admin'?await all('SELECT * FROM reports ORDER BY created DESC LIMIT 200'):[]})}
 if(route==='content-import'&&method==='POST'){staff();if(!Array.isArray(b.items)||!b.items.length||b.items.length>100)fail(400,'Import 1–100 complete question drafts at a time.');let incoming=b.items.map((item:any)=>validateDraft(item,topics));const signature=(i:Item)=>[i.subject,i.stem.toLowerCase().replace(/\s+/g,' ').trim(),i.passage?.paragraphs.join('\n')||''].join('|');const signatures=new Set(authoredItems.map(signature));for(const item of incoming){let key=signature(item);if(signatures.has(key))fail(409,'An exact question is already in the bank or this import.');signatures.add(key);if(item.passage){const conflict=[...authoredItems,...incoming].find(i=>i.setId===item.setId&&JSON.stringify(i.passage)!==JSON.stringify(item.passage));if(conflict)fail(409,'A shared passage ID must use exactly the same passage text, title, genre, and attribution.');}}await db.batch([...incoming.map((item:Item)=>stmt('INSERT INTO custom_content (id,owner,item,created) VALUES (?,?,?,?)',item.id,u.id,JSON.stringify(item),now())),log(u.id,'Question drafts imported',String(incoming.length))]);return json({saved:true,count:incoming.length,ids:incoming.map((i:Item)=>i.id),state:'draft'})}
 if(route==='content-review'&&method==='POST'){admin();let itemId=clean(b.id);if(!authoredItems.some(i=>i.id===itemId)&&!mathTopics.some(t=>'math:'+t.id===itemId))fail(404,'Content not found.');let state=['draft','reviewed','published','quarantined'].includes(b.state)?b.state:'draft';let notes=clean(b.notes||'',3000);if(['reviewed','published'].includes(state)&&notes.length<20)fail(400,'Record your editorial and scope review before publishing.');await db.batch([stmt('INSERT INTO content_reviews (id,state,notes,actor,created) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET state=excluded.state,notes=excluded.notes,actor=excluded.actor,created=excluded.created',itemId,state,notes,u.id,now()),log(u.id,'Content marked '+state,itemId)]);return json({saved:true})}
 if(route==='report'&&method==='POST'){let iid=clean(b.itemId);let a=await one('SELECT * FROM attempts WHERE id=?',clean(b.attemptId));if(!a||!await ownAttempt(a)||!JSON.parse(a.items).some((it:Item)=>it.id===iid))fail(403,'Question access denied.');await run('INSERT INTO reports (id,user_id,item_id,message,created) VALUES (?,?,?,?,?)',id(),u.id,iid,clean(b.message,2000),now());return json({saved:true})}
 if(path[0]==='lesson'&&path[1]&&method==='GET'){let topic:any=topics.find(t=>t.id===path[1]);if(!topic||(u.role==='student'&&topic.grade>Math.max(8,u.grade)))fail(404,'This lesson is not available for your track.');let item=topic.subject==='Math'?mathItem(topic.id,Math.floor(Math.random()*1e9)):eligible.find(i=>i.topic===topic.id&&i.grade<=Math.max(8,u.grade));if(item)await run('INSERT INTO exposures (id,user_id,item_id,source,created) VALUES (?,?,?,?,?)',id(),u.id,item.id,'worked-lesson',now());return json({title:topic.title,introduction:topic.subject==='Math'?'Read the whole situation, identify the requested quantity, and translate it into a relationship. Work through this example and verify the answer.':'Read every option against the entire question and the relevant text. An answer may be partly true yet fail to answer the precise question.',item:item?{...item,verify:undefined}:null});}
 if(route==='start'&&method==='POST'){if(!['student','teacher','admin'].includes(u.role))fail(403,'Active learning access is required.');let active=await one('SELECT * FROM attempts WHERE user_id=? AND state=\'in-progress\' LIMIT 1',u.id);if(active&&active.deadline&&active.deadline<=now()){await finish(active,'expired');active=null}if(active)return json({id:active.id,resumed:true});let startedAt=now(),seed=Math.floor(Math.random()*1e9),items:Item[]=[],title='',mode=b.mode==='mini'?'mini':'practice',aid:string|null=null,deadline:number|null=null;
 if(b.assignmentId){if(u.role!=='student')fail(403,'Use Preview for class assignments; My Learning creates personal work.');aid=clean(b.assignmentId);let a=await one('SELECT a.*,r.due recipient_due,r.attempt_limit recipient_limit FROM assignments a JOIN recipients r ON r.assignment_id=a.id WHERE a.id=? AND r.user_id=? AND a.state=\'published\' AND (a.published IS NULL OR a.published<=?)',aid,u.id,now());if(!a)fail(403,'Assignment access denied.');if(a.recipient_due&&a.recipient_due<now())fail(409,'The due date has passed. Ask your teacher for an extension.');let attemptsCount=await one('SELECT COUNT(*) total FROM attempts WHERE assignment_id=? AND user_id=?',aid,u.id);if(attemptsCount.total>=(a.recipient_limit??a.attempt_limit))fail(409,'The attempt limit has been reached.');items=JSON.parse(a.items);title=a.title;mode=a.mode;deadline=a.minutes?startedAt+a.minutes*60000:null;if(a.recipient_due)deadline=deadline?Math.min(deadline,a.recipient_due):a.recipient_due;
 }else if(b.mode==='diagnostic'){
  const past=await all('SELECT items FROM attempts WHERE user_id=?',u.id);const exposed=new Set(past.flatMap(a=>JSON.parse(a.items).filter((i:Item)=>i.subject==='ELA').map((i:Item)=>i.id)));
  const fresh=eligible.filter(i=>i.grade<=Math.max(8,u.grade)&&!exposed.has(i.id));
  items=buildDiagnostic(Math.max(8,u.grade),seed,b.startSubject,fresh);title='100-question SHSAT rehearsal';mode='diagnostic';deadline=startedAt+EXAM.standardMinutes*60000;
 }
 else if(b.followup){let source=await one('SELECT * FROM attempts WHERE id=? AND user_id=?',clean(b.followup.attemptId),u.id);let index=Number(b.followup.index);if(!source||!await released(source))fail(403,'Review access denied.');let original:Item=JSON.parse(source.items)[index];if(!original)fail(404,'Question not found.');if(original.subject==='Math'){items=[mathItem(original.topic,seed,2),mathItem(original.topic,seed+7919,3)]}else{let pool=eligible.filter(i=>i.grade<=Math.max(8,u.grade)&&i.topic===original.topic&&i.id!==original.id&&i.setId!==original.setId);if(pool.length<2)fail(409,'This skill needs two more reviewed questions in different contexts. Staff can publish them in Content review.');items=pool.slice(0,2).map((v,i)=>shuffled(v,seed+i));}title='Two-question follow-up';mode='followup';}
 else {let subject=b.subject==='ELA'?'ELA':'Math',topic=clean(b.topic||'mixed'),count=Math.min(30,Math.max(2,Number(b.count)||10));items=buildItems(subject,topic,count,Math.max(8,u.grade),seed);title=mode==='mini'?`${subject} mini diagnostic`:topics.find(t=>t.id===topic)?.title||`${subject} mixed practice`;if(mode==='mini')deadline=startedAt+Math.min(60,Math.max(5,Number(b.minutes)||20))*60000;}
 if(!aid&&['homework','classwork'].includes(b.mode)){mode=b.mode;title=clean(b.title||'',120);if(title.length<2)fail(400,'Give your personal work a custom title.');}const conditions={ownerRole:u.role,personal:!aid,seed,examVersion:EXAM.version,contentRelease:EXAM.contentRelease};let attemptId=id();try{await run('INSERT INTO attempts (id,user_id,assignment_id,title,mode,grade,items,answers,started,deadline,conditions) VALUES (?,?,?,?,?,?,?,?,?,?,?)',attemptId,u.id,aid,title,mode,Math.max(8,u.grade),JSON.stringify(items),'{}',startedAt,deadline,JSON.stringify(conditions));}catch(e:any){if(e.message?.includes('UNIQUE constraint')){const concurrent=await one('SELECT id FROM attempts WHERE user_id=? AND state=\'in-progress\' LIMIT 1',u.id);if(concurrent)return json({id:concurrent.id,resumed:true})}throw e}return json({id:attemptId})}
 if(path[0]==='attempt'&&path[1]){let a=await one('SELECT * FROM attempts WHERE id=?',path[1]);if(!a||!await ownAttempt(a))fail(403,'Attempt access denied.');if(method==='GET'){if(u.role==='admin'&&a.user_id!==u.id){const owner=await one('SELECT role FROM users WHERE id=?',a.user_id);if(owner&&owner.role!=='student')await run('INSERT INTO audit (id,actor,action,target,created) VALUES (?,?,?,?,?)',id(),u.id,'Authorized staff personal result inspection',a.id,now());}return json(await serialize(a));}if(a.user_id!==u.id)fail(403,'You cannot answer for another student.');if(a.state!=='in-progress')return json(await serialize(a));if(a.deadline&&a.deadline<=now()){await finish(a,'expired');return json(await serialize(a))};if(Number(b.revision)!==a.revision)fail(409,'Another tab has updated this attempt. Reload the saved attempt before continuing.');let items:Item[]=JSON.parse(a.items),answers=JSON.parse(a.answers),current=items[a.cursor];let allowed=current?.setId?items.map((it,i)=>it.setId===current.setId?i:-1).filter(i=>i>=0):[a.cursor];if(b.answers){for(let key of Object.keys(b.answers)){let index=Number(key),it=items[index],response=b.answers[key];if(!allowed.includes(index)||!it)fail(403,'A submitted question cannot be changed.');if(it.format==='single'){const choice=typeof response==='string'?/^option-(\d+)$/.exec(response):null;const selected=choice&&it.options?.[Number(choice[1])];if(!selected)fail(400,'Select an answer.');response=selected!.id;}if(it.format==='numeric'&&(typeof response!=='string'||response.length>80))fail(400,'Enter a numeric answer.');answers[index]=response;}}
 let cursor=a.cursor,state='in-progress',finished=null;if(b.action==='advance'){if(allowed.some(i=>answers[i]===undefined||String(answers[i]).trim()===''))fail(400,'Answer every question in the current set before submitting it.');cursor=Math.max(...allowed)+1;if(cursor>=items.length){state='submitted';finished=now()}}else if(b.action==='finish'){state='submitted';finished=now()}else if(b.action==='abandon'){state='abandoned';finished=now()}
 if(a.mode==='diagnostic'&&b.action==='advance'&&state==='in-progress'&&items[cursor]?.subject==='ELA'&&items[cursor]?.setId){
  const model=ability(items,answers,'ELA');const future=items.slice(cursor);const ids=[...new Set(future.filter(it=>it.subject==='ELA'&&it.setId).map(it=>it.setId))];
  const candidates=ids.map(setId=>({setId,group:future.filter(it=>it.setId===setId)})).filter(c=>c.group.length===5).sort((a,b)=>Math.abs(a.group.reduce((n,it)=>n+it.difficulty-2,0)/5-model.estimate)-Math.abs(b.group.reduce((n,it)=>n+it.difficulty-2,0)/5-model.estimate));
  const chosen=candidates[0];if(chosen&&chosen.setId!==items[cursor].setId){const location=items.findIndex((it,index)=>index>cursor&&it.setId===chosen.setId);const previous=items.slice(cursor,cursor+5);items.splice(cursor,5,...chosen.group);items.splice(location,5,...previous);}
 }
 if(a.mode==='diagnostic'&&b.action==='advance'&&state==='in-progress'&&items[cursor]?.subject==='Math'){
  const model=ability(items,answers,'Math');const served=items.slice(0,cursor).filter(i=>i.subject==='Math');const pool=mathTopics.filter(t=>t.grade<=a.grade&&states.get('math:'+t.id)==='published');
  const domains=[...new Set(pool.map(t=>t.domain))];const domain=domains[served.length%domains.length];const candidate=pool.filter(t=>t.domain===domain).sort((x,y)=>Math.abs(band(x.id)-2-model.estimate)-Math.abs(band(y.id)-2-model.estimate))[0];
  if(candidate){let next:Item|null=null;for(let k=0;k<30;k++){let v=mathItem(candidate.id,(Math.floor(a.started/1000)+cursor*7919+k*1009)>>>0,band(candidate.id));if(!served.some(it=>it.stem===v.stem)){next=v;break}}if(!next)fail(409,'The content reserve could not provide a distinct next question. Contact your teacher.');items[cursor]=next!;}
 }
 let notes=JSON.parse(a.notes);if(typeof b.note==='string')notes[current?.subject==='ELA'?'ELA':String(a.cursor)]=b.note.slice(0,10000);
 const result=await run('UPDATE attempts SET answers=?,cursor=?,state=?,finished=?,notes=?,items=?,revision=revision+1 WHERE id=? AND revision=? AND state=\'in-progress\'',JSON.stringify(answers),cursor,state,finished,JSON.stringify(notes),JSON.stringify(items),a.id,a.revision);if(!result.meta.changes)fail(409,'Another tab updated this attempt. Reload to recover the saved answers.');a={...a,items:JSON.stringify(items),answers:JSON.stringify(answers),cursor,notes:JSON.stringify(notes),revision:a.revision+1};if(state!=='in-progress'){await finish({...a,state:'in-progress'},state);a.state=state;a.finished=finished;let fresh=await one('SELECT * FROM attempts WHERE id=?',a.id);return json(await serialize(fresh))}return json(await serialize(a));}
 if(route==='mistake'&&method==='POST'){if(!['student','teacher','admin'].includes(u.role))fail(403,'Active learning access is required.');let m=await one('SELECT * FROM mistakes WHERE id=? AND user_id=?',clean(b.id),u.id);if(!m)fail(404,'Mistake not found.');let stage=b.reviewed?Math.min(3,m.stage+1):m.stage;await run('UPDATE mistakes SET reason=?,stage=?,review_at=? WHERE id=?',clean(b.reason||m.reason,500),stage,now()+[1,3,7,14][stage]*86400000,m.id);return json({saved:true})}
 if(route==='export'&&method==='GET'){let personalExport=new URL(req.url).searchParams.get('scope')==='personal';let rows=u.role==='student'||personalExport?await all('SELECT * FROM attempts WHERE user_id=?',u.id):u.role==='admin'?await all("SELECT a.* FROM attempts a JOIN users u ON u.id=a.user_id WHERE u.role='student'"):await all('SELECT DISTINCT a.* FROM attempts a JOIN memberships s ON s.user_id=a.user_id JOIN memberships t ON t.class_id=s.class_id JOIN classes c ON c.id=s.class_id WHERE t.user_id=? AND t.kind=\'teacher\' AND s.kind=\'student\' AND t.active=1 AND s.active=1 AND c.state=\'active\'',u.id);let exported=[];for(let a of rows)if(await released(a))exported.push({id:a.id,userId:a.user_id,title:a.title,started:a.started,finished:a.finished,state:a.state,summary:score(a),answers:JSON.parse(a.answers)});return json({center:defaults.center,exportedAt:now(),scope:u.role==='student'||personalExport?'Own released academic records':'Authorized academic records',attempts:exported})}
 fail(404,'This action is unavailable.');
 }catch(e:any){if(e instanceof HttpError)return json({error:e.message},e.status);if(e.message?.includes('UNIQUE constraint'))return json({error:'This username or record already exists. Nothing was duplicated.'},409);console.error('QST request failed',path.join('/'),e.message);return json({error:e instanceof Error&&!/SQL|D1|table|constraint/i.test(e.message)?e.message:'Unable to save or load this information. Please try again.'},400)}
}
