export const DIFFICULTIES=['Easy','Medium','Medium-Hard','Hard','Very Hard'];
export const ELA_SKILLS=['Main idea','Inference','Supporting evidence','Vocabulary','Author purpose','Tone','Structure','Literary analysis','Comparison','Argument','Grammar','Sentence structure','Organization','Revision'];
export const MATH_SKILLS=['Ratios','Proportions','Number systems','Expressions','Equations','Inequalities','Arithmetic','Fractions','Decimals','Percentages','Rates','Geometry','Coordinate geometry','Statistics','Probability','Data interpretation','Multi-step reasoning'];
export const DIAGNOSTIC={version:2,min:100,max:100,ELA:50,Math:50,reading:40,editing:10,passageSize:4,start:2} as const;
export const ELA_EDITING_SKILLS=['Grammar','Sentence structure','Organization','Revision'];
export type DiagnosticBlueprint={ELA:number;Math:number;reading:number;editing:number;total:number};
export const DIAGNOSTIC_BLUEPRINT:DiagnosticBlueprint={ELA:50,Math:50,reading:40,editing:10,total:100};
export type DiagnosticLevels={ELA:number;Math:number};
export type Question={id:string;subject:string;skill:string;difficulty:number;text:string;choices?:string[];correct:number|string;type?:string;passageId?:string;passage?:{title:string;content:string;type:string};explanation:string;breakthrough:string;commonTrap:string;distractorReasons?:string[];evidence?:string;templateId?:string;generationMethod?:string;estimatedTime?:number;subskill?:string};
export type Evidence={id?:string;skill:string;subject:string;difficulty:number;correct:number;seconds?:number;passageId?:string};
export function estimate(rows:Evidence[],prior=2.5){let ability=prior;for(const r of rows){const p=1/(1+Math.exp(-(ability-r.difficulty)));ability=Math.max(1,Math.min(5,ability+.75/Math.sqrt(1+rows.slice(0,rows.indexOf(r)).length/8)*(r.correct-p)))}return Math.round(ability*100)/100}
export function profile(rows:Evidence[]){const skills=[...ELA_SKILLS,...MATH_SKILLS].map(skill=>{const rs=rows.filter(r=>r.skill===skill);const n=rs.length,c=rs.reduce((s,r)=>s+r.correct,0);return{skill,subject:ELA_SKILLS.includes(skill)?'ELA':'Math',ability:estimate(rs),evidence:n,accuracy:n?Math.round(100*c/n):null,confidence:Math.min(95,Math.round(100*(1-Math.exp(-n/8)))),status:n>=8&&c/n>=.85&&rs.slice(-4).every(r=>r.correct)&&rs.some(r=>r.difficulty>=3&&r.correct)?'Mastered':n>=5&&c/n>=.65?'Improving':n>=2?'Practicing':'Needs Review'}});return{overall:estimate(rows),ELA:estimate(rows.filter(r=>r.subject==='ELA')),Math:estimate(rows.filter(r=>r.subject==='Math')),skills}}
export function diagnosticComposition(rows:{subject:string;passageId?:string}[]){const ELA=rows.filter(r=>r.subject==='ELA');return{ELA:ELA.length,Math:rows.filter(r=>r.subject==='Math').length,reading:ELA.filter(r=>r.passageId).length,editing:ELA.filter(r=>!r.passageId).length,total:rows.length}}
export function diagnosticStartingLevels(prior:Evidence[]):DiagnosticLevels{const level=(subject:string)=>{const rows=prior.filter(r=>r.subject===subject);return rows.length?Math.max(1,Math.min(5,Math.round(estimate(rows)))):DIAGNOSTIC.start};return{ELA:level('ELA'),Math:level('Math')}}
// Upgrade the blueprint around saved work, rather than replacing a student's
// existing questions. Older diagnostics occasionally contain lone passage
// questions; their remaining reading quota can therefore end with a short set.
export function diagnosticBlueprintForSavedQuestions(questions:Question[]):DiagnosticBlueprint{const counts=diagnosticComposition(questions);if(counts.ELA>50||counts.Math>50)throw new Error('Saved diagnostic exceeds its section capacity.');const editing=Math.max(DIAGNOSTIC.editing,counts.editing);return{...DIAGNOSTIC_BLUEPRINT,editing,reading:DIAGNOSTIC.ELA-editing}}
export function diagnosticNext(rows:Evidence[],levels:DiagnosticLevels={ELA:2,Math:2},blueprint:DiagnosticBlueprint=DIAGNOSTIC_BLUEPRINT){const counts=diagnosticComposition(rows),ela=rows.filter(r=>r.subject==='ELA');if(counts.reading<blueprint.reading)return{kind:'reading' as const,subject:'ELA',skill:undefined,difficulty:nextDifficulty(ela.filter(r=>r.passageId),levels.ELA),count:Math.min(DIAGNOSTIC.passageSize,blueprint.reading-counts.reading)};if(counts.editing<blueprint.editing)return{kind:'editing' as const,subject:'ELA',skill:ELA_EDITING_SKILLS[counts.editing%ELA_EDITING_SKILLS.length],difficulty:nextDifficulty(ela,levels.ELA),count:1};const math=rows.filter(r=>r.subject==='Math'),count=(skill:string)=>math.filter(r=>r.skill===skill).length,skill=[...MATH_SKILLS].sort((a,b)=>count(a)-count(b)||MATH_SKILLS.indexOf(a)-MATH_SKILLS.indexOf(b))[0];return{kind:'math' as const,subject:'Math',skill,difficulty:nextDifficulty(math,levels.Math),count:1}}
export function diagnosticDone(rows:Evidence[],blueprint:DiagnosticBlueprint=DIAGNOSTIC_BLUEPRINT){const counts=diagnosticComposition(rows);return counts.total===blueprint.total&&counts.ELA===blueprint.ELA&&counts.Math===blueprint.Math&&counts.reading===blueprint.reading&&counts.editing===blueprint.editing}
export function diagnosticValidationErrors(questions:Question[],blueprint:DiagnosticBlueprint=DIAGNOSTIC_BLUEPRINT,legacyOrder=false){const errors:string[]=[],counts=diagnosticComposition(questions);if(counts.total!==100||new Set(questions.map(q=>q.id)).size!==100)errors.push('A diagnostic needs 100 distinct questions.');if(counts.ELA!==50||counts.Math!==50||counts.reading!==blueprint.reading||counts.editing!==blueprint.editing)errors.push('A diagnostic must contain its complete ELA and Math sections.');if(questions.some(q=>q.subject==='ELA'&&!q.passageId&&!ELA_EDITING_SKILLS.includes(q.skill)))errors.push('Standalone ELA questions must assess revising or editing.');if(!legacyOrder){if(questions.slice(0,40).some(q=>q.subject!=='ELA'||!q.passageId)||questions.slice(40,50).some(q=>q.subject!=='ELA'||q.passageId)||questions.slice(50).some(q=>q.subject!=='Math'))errors.push('Diagnostic sections are out of order.');const passages=new Set<string>();for(let i=0;i<40;i+=4){const group=questions.slice(i,i+4),pid=group[0]?.passageId;if(!pid||passages.has(pid)||group.length!==4||group.some(q=>q.passageId!==pid||q.difficulty!==group[0].difficulty))errors.push('Keep four questions from each distinct passage together at one level.');if(pid)passages.add(pid)}}return errors}
export function matches(q:Question,answer:unknown){if(q.type==='grid'){const raw=String(answer).trim();const parts=raw.split('/');const value=parts.length===2?Number(parts[0])/Number(parts[1]):Number(raw);return raw!==''&&Number.isFinite(value)&&Math.abs(value-Number(q.correct))<.000051}return Number.isInteger(Number(answer))&&Number(answer)===q.correct}
export function publicQuestion(q:Question){const{correct,explanation,breakthrough,commonTrap,distractorReasons,evidence,...safe}=q;return safe}
export function validate(q:Question){const errors:string[]=[];if(!q.id||!q.text||!q.skill||!['Math','ELA'].includes(q.subject))errors.push('Missing identity, prompt, subject, or skill.');if(!Number.isInteger(q.difficulty)||q.difficulty<1||q.difficulty>5)errors.push('Difficulty must be 1–5.');if(!q.explanation||!q.breakthrough||!q.commonTrap)errors.push('Explanation, breakthrough, and common trap are required.');if(q.type==='grid'){if(!Number.isFinite(Number(q.correct)))errors.push('Grid answer must be numeric.')}else if(!q.choices||q.choices.length!==4||new Set(q.choices.map(x=>x.trim().toLowerCase())).size!==4||!Number.isInteger(q.correct)||Number(q.correct)<0||Number(q.correct)>3)errors.push('Four distinct choices and one correct index are required.');if(q.passage&&(!q.evidence||!q.passage.content.includes(q.evidence)))errors.push('Evidence must occur in the passage.');return errors}
export function nextDifficulty(rows:Evidence[],fallback=2){if(!rows.length)return fallback;const last=rows.slice(-3);const avg=last.reduce((n,r)=>n+r.correct,0)/last.length;return Math.max(1,Math.min(5,rows.at(-1)!.difficulty+(avg>=2/3?1:avg<=1/3?-1:0)))}
