export const DIFFICULTIES=['Easy','Medium','Medium-Hard','Hard','Very Hard'];
export const ELA_SKILLS=['Main idea','Inference','Supporting evidence','Vocabulary','Author purpose','Tone','Structure','Literary analysis','Comparison','Argument','Grammar','Sentence structure','Organization','Revision'];
export const MATH_SKILLS=['Ratios','Proportions','Number systems','Expressions','Equations','Inequalities','Arithmetic','Fractions','Decimals','Percentages','Rates','Geometry','Coordinate geometry','Statistics','Probability','Data interpretation','Multi-step reasoning'];
export const DIAGNOSTIC={min:28,max:40,coverage:14,stability:.08,start:2};
export type Question={id:string;subject:string;skill:string;difficulty:number;text:string;choices?:string[];correct:number|string;type?:string;passageId?:string;passage?:{title:string;content:string;type:string};explanation:string;breakthrough:string;commonTrap:string;distractorReasons?:string[];evidence?:string;templateId?:string;generationMethod?:string;estimatedTime?:number;subskill?:string};
export type Evidence={skill:string;subject:string;difficulty:number;correct:number;seconds?:number};
export function estimate(rows:Evidence[],prior=2.5){let ability=prior;for(const r of rows){const p=1/(1+Math.exp(-(ability-r.difficulty)));ability=Math.max(1,Math.min(5,ability+.75/Math.sqrt(1+rows.slice(0,rows.indexOf(r)).length/8)*(r.correct-p)))}return Math.round(ability*100)/100}
export function profile(rows:Evidence[]){const skills=[...ELA_SKILLS,...MATH_SKILLS].map(skill=>{const rs=rows.filter(r=>r.skill===skill);const n=rs.length,c=rs.reduce((s,r)=>s+r.correct,0);return{skill,subject:ELA_SKILLS.includes(skill)?'ELA':'Math',ability:estimate(rs),evidence:n,accuracy:n?Math.round(100*c/n):null,confidence:Math.min(95,Math.round(100*(1-Math.exp(-n/8)))),status:n>=8&&c/n>=.85&&rs.slice(-4).every(r=>r.correct)&&rs.some(r=>r.difficulty>=3&&r.correct)?'Mastered':n>=5&&c/n>=.65?'Improving':n>=2?'Practicing':'Needs Review'}});return{overall:estimate(rows),ELA:estimate(rows.filter(r=>r.subject==='ELA')),Math:estimate(rows.filter(r=>r.subject==='Math')),skills}}
export function diagnosticNext(rows:Evidence[]){const coverage=['Ratios','Main idea','Equations','Inference','Geometry','Vocabulary','Statistics','Supporting evidence','Percentages','Grammar','Probability','Author purpose','Rates','Structure'];const count=(s:string)=>rows.filter(r=>r.skill===s).length;const skill=[...coverage].sort((a,b)=>count(a)-count(b)||coverage.indexOf(a)-coverage.indexOf(b))[0];const subject=ELA_SKILLS.includes(skill)?'ELA':'Math';const sr=rows.filter(r=>r.skill===skill);const subjectAbility=estimate(rows.filter(r=>r.subject===subject));const ability=sr.length?estimate(sr,subjectAbility):subjectAbility;return{skill,subject,difficulty:rows.length?Math.max(1,Math.min(5,Math.round(ability))):DIAGNOSTIC.start}}
export function diagnosticDone(rows:Evidence[]){return rows.length>=DIAGNOSTIC.max||(rows.length>=DIAGNOSTIC.min&&new Set(rows.map(r=>r.skill)).size>=DIAGNOSTIC.coverage&&Math.abs(estimate(rows)-estimate(rows.slice(0,-3)))<=DIAGNOSTIC.stability)}
export function matches(q:Question,answer:unknown){if(q.type==='grid'){const raw=String(answer).trim();const parts=raw.split('/');const value=parts.length===2?Number(parts[0])/Number(parts[1]):Number(raw);return raw!==''&&Number.isFinite(value)&&Math.abs(value-Number(q.correct))<.000051}return Number.isInteger(Number(answer))&&Number(answer)===q.correct}
export function publicQuestion(q:Question){const{correct,explanation,breakthrough,commonTrap,distractorReasons,evidence,...safe}=q;return safe}
export function validate(q:Question){const errors:string[]=[];if(!q.id||!q.text||!q.skill||!['Math','ELA'].includes(q.subject))errors.push('Missing identity, prompt, subject, or skill.');if(!Number.isInteger(q.difficulty)||q.difficulty<1||q.difficulty>5)errors.push('Difficulty must be 1–5.');if(!q.explanation||!q.breakthrough||!q.commonTrap)errors.push('Explanation, breakthrough, and common trap are required.');if(q.type==='grid'){if(!Number.isFinite(Number(q.correct)))errors.push('Grid answer must be numeric.')}else if(!q.choices||q.choices.length!==4||new Set(q.choices.map(x=>x.trim().toLowerCase())).size!==4||!Number.isInteger(q.correct)||Number(q.correct)<0||Number(q.correct)>3)errors.push('Four distinct choices and one correct index are required.');if(q.passage&&(!q.evidence||!q.passage.content.includes(q.evidence)))errors.push('Evidence must occur in the passage.');return errors}
export function nextDifficulty(rows:Evidence[],fallback=2){if(!rows.length)return fallback;const last=rows.slice(-3);const avg=last.reduce((n,r)=>n+r.correct,0)/last.length;return Math.max(1,Math.min(5,rows.at(-1)!.difficulty+(avg>=2/3?1:avg<=1/3?-1:0)))}
