export type Subtopic={id:string;label:string;subject:'Math'|'ELA';domain:string;skill:string;kind:'math'|'reading'|'editing';target:number;standards:string[]};
type Group=[Subtopic['kind'],string,string,string];
const groups:Group[]=[
 ['math','Ratios and proportional relationships','Ratios','Ratios;Equivalent ratios;Part-to-part ratios;Part-to-whole ratios;Ratio tables;Missing ratio quantities'],
 ['math','Ratios and proportional relationships','Rates','Unit rates;Fractional unit rates;Rates involving different units'],
 ['math','Ratios and proportional relationships','Proportions','Proportional relationships;Constant of proportionality;Proportional tables;Proportional graphs;Proportional equations;Identifying proportional relationships;Identifying non-proportional relationships;Multi-step proportional reasoning'],
 ['math','Ratios and proportional relationships','Percentages','Percent of a quantity;Finding a percent;Finding a part;Finding a whole;Percent increase;Percent decrease;Discounts;Markups;Markdowns;Sales tax;Tips;Gratuities;Commissions;Fees;Simple interest;Percent error;Multi-step percent situations'],
 ['math','Number system','Number systems','Positive integers;Negative integers;Rational numbers;Terminating decimals;Repeating decimals;Fraction-to-decimal conversions;Decimal-to-fraction conversions;Comparing rational numbers;Ordering rational numbers;Absolute value;Opposites;Number lines;Distance on number lines;Factors;Multiples;Prime numbers;Composite numbers;Prime factorization;Greatest common factor;Least common multiple;Divisibility;Properties of operations'],
 ['math','Number system','Fractions','Fractions;Mixed numbers;Improper fractions;Fraction addition;Fraction subtraction;Fraction multiplication;Fraction division;Equivalent fractions;Simplifying fractions;Reciprocals'],
 ['math','Number system','Arithmetic','Integer addition;Integer subtraction;Integer multiplication;Integer division;Mixed rational-number operations;Order of operations'],
 ['math','Number system','Decimals','Decimals;Decimal operations'],
 ['math','Expressions','Expressions','Variables;Constants;Coefficients;Terms;Numerical expressions;Algebraic expressions;Evaluating expressions;Substitution;Translating words into expressions;Translating expressions into words;Combining like terms;Distributive property;Expanding expressions;Simple factoring;Equivalent expressions;Rewriting expressions;Rational-number expressions;Multi-step expression evaluation;Recognizing expression structure'],
 ['math','Equations and inequalities','Equations','One-step equations;Two-step equations;Grade-appropriate multi-step equations;Rational-number equations;Equations containing parentheses;Equations from word problems;Equations from proportional relationships;Checking solutions;Unknown quantities;Algebraic multi-step problems'],
 ['math','Equations and inequalities','Inequalities','Inequality symbols;Writing inequalities;Solving inequalities;Rational-number inequalities;Word-problem inequalities;Number-line representations;Solution sets;Real-world inequality situations'],
 ['math','Geometry','Geometry','Angle measurement;Adjacent angles;Vertical angles;Complementary angles;Supplementary angles;Unknown angles;Angle relationships;Parallel lines;Perpendicular lines;Intersecting lines;Triangle classification;Triangle angle relationships;Triangle area;Triangle dimensions;Possible triangles;Rectangles;Squares;Parallelograms;Trapezoids;Polygons;Perimeter;Area;Composite figures;Missing dimensions;Radius;Diameter;Circumference;Circle area;Pi;Multi-step circle problems;Cubes;Rectangular prisms;Appropriate prisms;Surface area;Volume;Three-dimensional figures;Appropriate cross-sections;Scale factors;Scale drawings;Actual dimensions;Drawing dimensions'],
 ['math','Geometry','Coordinate geometry','Coordinate-plane geometry'],
 ['math','Statistics','Statistics','Statistical questions;Populations;Samples;Random sampling;Representative samples;Biased samples;Sampling variability;Drawing conclusions from samples;Data sets;Mean;Median;Mode;Range;Measures of center;Measures of variability;Comparing populations;Comparing distributions;Statistical inference'],
 ['math','Statistics','Data interpretation','Frequency tables;Graphs;Dot plots;Histograms;Appropriate box plots'],
 ['math','Probability','Probability','Simple probability;Theoretical probability;Experimental probability;Probability models;Sample spaces;Compound events;Organized lists;Tables;Tree diagrams;Simulations;Multi-step probability reasoning'],
 ['math','Multi-step reasoning','Multi-step reasoning','Multi-step mathematical reasoning;Ratios and percent;Fractions and equations;Geometry and percent;Rates and proportions;Statistics and percent;Area and algebra;Unit rates and multi-step word problems'],
 ['reading','Reading comprehension','Main idea','Main idea;Central idea;Theme;Summarizing'],
 ['reading','Reading comprehension','Supporting evidence','Supporting details;Key details;Explicit information;Textual evidence;Best evidence'],
 ['reading','Reading comprehension','Inference','Implicit information;Inference;Drawing conclusions'],
 ['reading','Literary analysis','Literary analysis','Character traits;Character motivation;Character development;Character relationships;Conflict;Setting;Plot;Sequence;Cause and effect;Development of individuals;Development of events;Development of ideas;Narrator;Figurative language;Metaphor;Simile;Personification;Imagery;Symbolism;Irony'],
 ['reading','Author craft','Author purpose',"Author's purpose;Point of view;Perspective"],
 ['reading','Author craft','Tone','Tone;Mood;Word choice;Diction;Connotation;Denotation'],
 ['reading','Vocabulary','Vocabulary','Vocabulary in context;Context clues;Multiple-meaning words'],
 ['reading','Structure','Structure','Text structure;Paragraph function;Sentence function'],
 ['reading','Argument','Argument','Claims;Reasons;Evidence;Counterclaims;Evaluating arguments'],
 ['reading','Comparison','Comparison',"Comparing texts;Comparing perspectives;Comparing themes;Comparing central ideas;Comparing authors' approaches"],
 ['editing','Revising','Revision','Main claim;Supporting details;Relevant information;Irrelevant information;Precision;Concision;Redundancy;Wordiness;Tone;Audience;Purpose;Evidence;Sentence addition;Sentence deletion;Sentence replacement;Style;Clarity'],
 ['editing','Revising','Organization','Introductions;Conclusions;Topic sentences;Sentence placement;Paragraph placement;Organization;Cohesion;Coherence;Transitions;Reordering'],
 ['editing','Language','Grammar','Subject-verb agreement;Pronoun agreement;Pronoun case;Pronoun reference;Verb tense;Tense consistency;Modifiers;Adjectives;Adverbs;Commas;Apostrophes;Possessives;Quotation marks;Dialogue punctuation;Capitalization;Standard English usage;Commonly confused words'],
 ['editing','Language','Sentence structure','Phrases;Clauses;Independent clauses;Dependent clauses;Fragments;Run-ons;Comma splices;Sentence combining'],
];
const slug=(value:string)=>value.toLowerCase().replace(/['’]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export const SUBTOPICS:Subtopic[]=groups.flatMap(([kind,domain,skill,labels])=>labels.split(';').map(label=>({id:(kind==='math'?'math':'ela-'+kind)+'-'+slug(label),label,subject:kind==='math'?'Math' as const:'ELA' as const,domain,skill,kind,target:2000,standards:kind==='math'?[domain==='Geometry'?'NY-7.G':domain==='Statistics'?'NY-7.SP':domain==='Probability'?'NY-6.SP/NY-7.SP':domain==='Expressions'||domain==='Equations and inequalities'?'NY-7.EE':domain==='Number system'?'NY-6.NS/NY-7.NS':'NY-7.RP']:['NY-7R/NY-7L']})));
export function findSubtopic(value:string|undefined){if(!value)return undefined;const exact=SUBTOPICS.find(topic=>topic.id===value);return exact||SUBTOPICS.find(topic=>slug(topic.label)===slug(value));}
export function subtopicsFor(subject?:string,skill?:string){return SUBTOPICS.filter(topic=>(!subject||subject==='Mixed'||topic.subject===subject)&&(!skill||skill==='all'||topic.skill===skill));}
export const CONTENT_GOAL_PER_SUBTOPIC=2000;
export const PASSAGE_GENRES=['Poetry','Adventure','Historical fiction','Mystery','Myth','Science fiction','Realistic fiction','Creative nonfiction','Science','History','Biography','Memoir','Journalism','Speech','Opinion','Expository','Argumentative','Technology','Art','Literature','Economics'];
