import {Question,MATH_SKILLS} from './assessment';
const round=(n:number)=>Math.round(n*10000)/10000;
function rng(seed:number){let x=seed|0;return()=>{x=(Math.imul(x,1664525)+1013904223)|0;return(x>>>0)/4294967296}}
export function mathQuestion(skill:string,d:number,seed:number,variant=seed%2):Question{const r=rng(seed),n=(a:number,b:number)=>a+Math.floor(r()*(b-a+1));let a=n(2,8+d*5),b=n(2,7+d*2),c=n(2,10),answer=0,text='',explanation='',breakthrough='',trap='',template=skill+'-'+variant;switch(skill){
case 'Ratios':if(variant===0){answer=a*c;text=`A club has ${a} art students for every ${b} music students. If there are ${b*c} music students, how many art students are there?`;explanation=`The scale factor is ${b*c} ÷ ${b} = ${c}. Multiply the art part by the same factor: ${a} × ${c} = ${answer}.`}else{answer=(a+b)*c;text=`The ratio of red to blue beads is ${a}:${b}. There are ${a*c} red beads. How many beads are there in all?`;explanation=`There are ${c} copies of the ratio. Each copy has ${a+b} beads, so the total is (${a} + ${b}) × ${c} = ${answer}.`}break;
case 'Proportions':if(variant===0){answer=a*c;text=`${b} identical notebooks cost $${a*b}. At that rate, what is the cost of ${c} notebooks?`;explanation=`Unit cost = ${a*b} ÷ ${b} = $${a}. For ${c} notebooks: ${c} × ${a} = $${answer}.`}else{answer=b*c;text=`A scale drawing uses ${a} cm for ${b} m. A wall measures ${a*c} cm on the drawing. What is its real length, in meters?`;explanation=`${a*c} ÷ ${a} = ${c} scale units. Multiply by ${b} m per unit: ${answer} m.`}break;
case 'Number systems':if(variant===0){answer=-a+b-c;text=`What is the value of −${a} + ${b} − ${c}?`;explanation=`Combine the negative terms: −${a} − ${c} = −${a+c}. Add ${b} to get ${answer}.`}else{answer=a*a-b*b;text=`What is the value of ${a}² − ${b}²?`;explanation=`Square each number first: ${a*a} − ${b*b} = ${answer}.`}break;
case 'Expressions':if(variant===0){answer=a*c+b;text=`If x = ${c}, what is the value of ${a}x + ${b}?`;explanation=`Substitute ${c} for x: ${a}(${c}) + ${b} = ${a*c} + ${b} = ${answer}.`}else{answer=(a+b)*c-b;text=`For x = ${c}, evaluate ${a}(x + ${b}) − ${b}(${a+1} − x).`;answer=a*(c+b)-b*(a+1-c);explanation=`First evaluate parentheses: ${a}(${c+b}) − ${b}(${a+1-c}). Multiply and subtract to get ${answer}.`}break;
case 'Equations':if(variant===0){answer=c;text=`Solve for x: ${a}x + ${b} = ${a*c+b}.`;explanation=`Subtract ${b} from both sides: ${a}x = ${a*c}. Divide both sides by ${a}: x = ${c}.`}else{answer=c;text=`Solve for x: ${a}(x − ${b}) = ${a*(c-b)}.`;explanation=`Divide by ${a}: x − ${b} = ${c-b}. Add ${b}: x = ${c}.`}break;
case 'Inequalities':answer=c+1;text=`What is the smallest integer x that satisfies ${a}x − ${b} > ${a*c-b}?`;explanation=`Add ${b}, then divide by positive ${a}: x > ${c}. The smallest integer greater than ${c} is ${answer}.`;break;
case 'Arithmetic':if(variant===0){answer=a*b+c;text=`Evaluate ${a} × ${b} + ${c}.`;explanation=`Multiply before adding: ${a*b} + ${c} = ${answer}.`}else{answer=(a+b)*c;text=`Evaluate (${a} + ${b}) × ${c}.`;explanation=`Evaluate parentheses first: ${a+b} × ${c} = ${answer}.`}break;
case 'Fractions':if(variant===0){answer=round((a+b)/(b*c));text=`What is ${a}/${b*c} + 1/${c}? Give a decimal or fraction.`;explanation=`Use denominator ${b*c}. The second fraction becomes ${b}/${b*c}. Add numerators to get ${a+b}/${b*c}, which is approximately ${answer}.`}else{answer=round(a/b*c);text=`A ribbon is ${a}/${b} meter long. What is the combined length, in meters, of ${c} such ribbons? Give a decimal or fraction.`;explanation=`Multiply ${a}/${b} by ${c}: ${a*c}/${b} ≈ ${answer}.`}break;
case 'Decimals':if(variant===0){answer=round(a/10+b/100);text=`Evaluate ${(a/10).toFixed(1)} + ${(b/100).toFixed(2)}.`;explanation=`Align decimal places: ${(a/10).toFixed(2)} + ${(b/100).toFixed(2)} = ${answer}.`}else{answer=round(a*b/100);text=`Evaluate ${(a/10).toFixed(1)} × ${(b/10).toFixed(1)}.`;explanation=`Multiply the whole numbers: ${a} × ${b} = ${a*b}. Divide by 100 for two decimal places: ${answer}.`}break;
case 'Percentages':{const price=a*20,percent=n(1,7)*5;answer=round(price*(1-percent/100));text=`A jacket priced at $${price} is discounted by ${percent}%. What is the sale price, in dollars?`;explanation=`The discount is ${percent/100} × ${price} = $${price*percent/100}. Subtract it from the original price: ${price} − ${price*percent/100} = $${answer}.`;break}
case 'Rates':if(variant===0){answer=a*c;text=`A cyclist travels ${a*b} kilometers in ${b} hours at a constant speed. How far, in kilometers, will the cyclist travel in ${c} hours?`;explanation=`Speed = ${a*b} ÷ ${b} = ${a} km/h. Distance = ${a} × ${c} = ${answer} km.`}else{answer=round(b/a);text=`A pump fills ${a} liters each minute. How many minutes does it take to fill a ${b}-liter tank?`;explanation=`Time = volume ÷ rate = ${b} ÷ ${a} ≈ ${answer} minutes.`}break;
case 'Geometry':if(variant===0){answer=a*b-a*c/2;text=`A rectangle is ${a} cm long and ${b+c} cm wide. A right triangle with base ${a} cm and height ${c} cm is removed. What area remains, in square centimeters?`;answer=a*(b+c)-a*c/2;explanation=`Rectangle area = ${a} × ${b+c} = ${a*(b+c)}. Removed triangle area = ½ × ${a} × ${c} = ${a*c/2}. Subtract to get ${answer} cm².`}else{answer=a*b*c;text=`A rectangular box has length ${a} cm, width ${b} cm, and height ${c} cm. What is its volume in cubic centimeters?`;explanation=`Volume = length × width × height = ${a} × ${b} × ${c} = ${answer} cm³.`}break;
case 'Coordinate geometry':if(variant===0){answer=round(b/a);text=`A line passes through (0, ${c}) and (${a}, ${c+b}). What is its slope?`;explanation=`Slope = change in y ÷ change in x = (${c+b} − ${c}) ÷ (${a} − 0) = ${b}/${a} ≈ ${answer}.`}else{answer=a+b;text=`Point P is (−${a}, ${c}) and point Q is (${b}, ${c}). What is the distance between P and Q?`;explanation=`The y-coordinates agree. The horizontal distance is ${b} − (−${a}) = ${a+b}.`}break;
case 'Statistics':if(variant===0){answer=round((a+b+c)/3);text=`Find the mean of ${a}, ${b}, and ${c}. Round to four decimal places if needed.`;explanation=`Add the three numbers: ${a+b+c}. Divide by 3: ${answer}.`}else{const values=[a,b,c,a+2,b+3].sort((x,y)=>x-y);answer=values[2];text=`What is the median of ${values.join(', ')}?`;explanation=`The data are already ordered. With five values, the median is the third value, ${answer}.`}break;
case 'Probability':answer=round(a/(a+b));text=`A bag contains ${a} green and ${b} yellow counters. One counter is drawn at random. What is the probability of green? Give a fraction or decimal rounded to four places.`;explanation=`Favorable outcomes = ${a}. Total = ${a+b}. Probability = ${a}/${a+b} ≈ ${answer}.`;break;
case 'Data interpretation':if(variant===0){answer=b*c;text=`A library recorded ${a*c} visits on Monday and ${(a+b)*c} on Tuesday. How many more visits were recorded on Tuesday?`;explanation=`Subtract Monday from Tuesday: ${(a+b)*c} − ${a*c} = ${answer}.`}else{answer=round(a/(a+b)*100);text=`A survey recorded ${a*10} votes for option A and ${b*10} for option B. What percent of all votes were for A? Round to four decimal places if needed.`;explanation=`Total votes = ${(a+b)*10}. Divide A votes by total and multiply by 100: ${a*10}/${(a+b)*10} × 100 ≈ ${answer}%.`}break;
default:c=Math.min(c,a*b-1);answer=a*b-c;text=`A school buys ${a} boxes with ${b} pencils each and distributes ${c} pencils. How many pencils remain?`;explanation=`Find the initial count: ${a} × ${b} = ${a*b}. Subtract the ${c} distributed: ${answer}.`;
}

if(d>=3){switch(skill){
case 'Ratios':answer=a*c;text=`A shipment has red and blue folders in the ratio ${a}:${b}. There are ${(a+b)*c} folders altogether. After ${b*c} blue folders are removed, how many red folders remain?`;explanation=`One ratio bundle has ${a+b} folders. There are ${(a+b)*c} ÷ ${a+b} = ${c} bundles. Red folders = ${a} × ${c} = ${answer}; removing blue folders does not change the red count.`;break;
case 'Proportions':answer=c*a;text=`${a} identical pumps drain a tank in ${b*c} minutes. At the same rate, how many minutes would ${b} pumps need?`;explanation=`The job requires ${a*b*c} pump-minutes. With ${b} pumps, time is ${a*b*c} ÷ ${b} = ${answer} minutes. Fewer pumps require more time.`;break;
case 'Number systems':answer=-a*a+b*c;text=`Evaluate −${a}² + (−${b})(−${c}).`;explanation=`Exponentiation comes before the leading minus: −${a}² = −${a*a}. The product of two negatives is ${b*c}. Add to get ${answer}.`;break;
case 'Expressions':answer=a*(c-b)+b*(c+a);text=`If x = ${c}, evaluate ${a}(x − ${b}) + ${b}(x + ${a}).`;explanation=`Substitute x = ${c}. The terms are ${a*(c-b)} and ${b*(c+a)}. Their sum is ${answer}. You may also distribute first; the constant terms cancel.`;break;
case 'Equations':answer=c;text=`Solve for x: ${a+b}x − ${a*c} = ${b}x.`;explanation=`Subtract ${b}x from both sides: ${a}x − ${a*c} = 0. Add ${a*c} and divide by ${a} to find x = ${answer}.`;break;
case 'Inequalities':answer=c-1;text=`What is the greatest integer x satisfying −${a}x + ${b} > ${b-a*c}?`;explanation=`Subtract ${b}: −${a}x > −${a*c}. Dividing by a negative reverses the inequality, so x < ${c}. The greatest allowed integer is ${answer}.`;break;
case 'Arithmetic':answer=(a+b)*c-a*a;text=`Evaluate (${a} + ${b}) × ${c} − ${a}².`;explanation=`Parentheses give ${a+b}. The product is ${(a+b)*c} and the square is ${a*a}. Subtract to obtain ${answer}.`;break;
case 'Fractions':answer=round(a*c*(b-1)/b);text=`A tank holds ${a*b*c} liters. One student uses 1/${b} of the water. Another uses 1/${b} of what remains. How many liters does the second student use?`;explanation=`After the first use, ${a*b*c} × (${b-1}/${b}) = ${a*c*(b-1)} liters remain. Take 1/${b} of that amount: ${a*c*(b-1)}/${b} ≈ ${answer}. The second fraction applies to the remaining amount, not the original.`;break;
case 'Decimals':answer=round(a*b/100+c/10);text=`A shop buys ${(a/10).toFixed(1)} kilograms of flour at ${(b/10).toFixed(1)} per kilogram and pays a ${(c/10).toFixed(1)} delivery fee. What is the total cost in dollars?`;explanation=`Flour cost = ${a/10} × ${b/10} = ${a*b/100}. Add delivery ${c/10} to get ${answer}.`;break;
case 'Percentages':{const price=a*20,discount=b*5,tax=c;answer=round(price*(1-discount/100)*(1+tax/100));text=`An item costs ${price}. It is discounted by ${discount}%, then a ${tax}% tax is applied to the discounted price. What is the final cost, in dollars? Round to four decimal places if needed.`;explanation=`Discounted price = ${price} × ${1-discount/100} = ${price*(1-discount/100)}. Apply tax to that price: multiply by ${1+tax/100} to get ${answer}. Percent changes multiply; do not simply subtract their rates.`;break}
case 'Rates':answer=round(2*a*b/(a+b));text=`A cyclist rides ${a*b} kilometers at ${a} km/h, then returns the same distance at ${b} km/h. What is the average speed for the whole trip? Round to four decimal places if needed.`;explanation=`Outgoing time = ${b} hours and return time = ${a} hours. Total distance = ${2*a*b} km; total time = ${a+b} hours. Average speed = ${2*a*b}/${a+b} ≈ ${answer} km/h. The two speeds are not averaged directly.`;break;
case 'Geometry':answer=(a+b)*(b+c)-b*c;text=`A rectangular garden is ${a+b} meters long and ${b+c} meters wide. A ${b}-by-${c}-meter rectangular pond is inside it. What is the garden area excluding the pond, in square meters?`;explanation=`Whole area = ${a+b} × ${b+c} = ${(a+b)*(b+c)}. Pond area = ${b} × ${c} = ${b*c}. Subtract to find ${answer} m².`;break;
case 'Coordinate geometry':answer=a*b/2;text=`A triangle has vertices (${c}, ${c}), (${c+a}, ${c}), and (${c}, ${c+b}). What is its area?`;explanation=`The horizontal base is ${a} units and the perpendicular height is ${b}. Triangle area = ½ × ${a} × ${b} = ${answer} square units. The offset coordinates do not change these lengths.`;break;
case 'Statistics':answer=4*c-a-b;text=`Four numbers have mean ${c}. Three of the numbers are ${a}, ${b}, and 0. What is the fourth number?`;explanation=`The four values must total 4 × ${c} = ${4*c}. The known values total ${a+b}. Subtract to get ${answer}. A negative missing value is allowed.`;break;
case 'Probability':answer=round(a*(a-1)/((a+b)*(a+b-1)));text=`A bag has ${a} green and ${b} yellow counters. Two are drawn without replacement. What is the probability both are green? Give a fraction or decimal rounded to four places.`;explanation=`First green probability = ${a}/${a+b}. After a green draw, second green probability = ${a-1}/${a+b-1}. Multiply: ${a*(a-1)}/${(a+b)*(a+b-1)} ≈ ${answer}. The counts change because there is no replacement.`;break;
case 'Data interpretation':answer=round((a+c)/(a+b)*100);text=`A survey records ${a*10} votes for A and ${b*10} for B. Then ${Math.min(c,b)*10} voters change from B to A. What percent now favor A? Round to four decimal places if needed.`;answer=round((a+Math.min(c,b))/(a+b)*100);explanation=`The total stays ${(a+b)*10}. A now has ${(a+Math.min(c,b))*10} votes. Divide by the unchanged total and multiply by 100: approximately ${answer}%.`;break;
default:{const adult=a+b,child=b,adults=c,children=a,total=adult*adults+child*children;answer=adults;text=`A show sells ${adults+children} tickets. Adult tickets cost ${adult} and child tickets cost ${child}. Revenue is ${total}. How many adult tickets were sold?`;explanation=`If all tickets were child tickets, revenue would be ${(adults+children)*child}. The extra ${total-(adults+children)*child} comes from adult tickets, each costing ${adult-child} more. Divide: ${total-(adults+children)*child} ÷ ${adult-child} = ${answer}.`}
}}
const strategies:Record<string,string>={'Ratios':'A ratio is a bundle of parts. Find the scale factor, then apply it to every part.','Proportions':'Find a unit rate or scale factor first; keep the units consistent.','Number systems':'Track signs carefully, and apply exponents before addition.','Expressions':'Replace each variable with its value before calculating.','Equations':'Undo operations in reverse order, doing the same thing to both sides.','Inequalities':'A strict inequality excludes its boundary. Check the nearest allowed integer.','Arithmetic':'Parentheses first, then multiplication and division, then addition and subtraction.','Fractions':'Equivalent fractions describe the same amount. Use common denominators for addition.','Decimals':'Place value matters: align decimals for addition and count decimal places for multiplication.','Percentages':'A discount leaves (100 − percent)% of the original price.','Rates':'Use distance = rate × time, and check that the units cancel.','Geometry':'Sketch the whole shape and each removed piece before combining their areas.','Coordinate geometry':'Measure coordinate changes. Subtracting a negative adds distance.','Statistics':'Mean uses every value; median uses the middle of an ordered list.','Probability':'Probability is favorable outcomes divided by all equally likely outcomes.','Data interpretation':'Identify the total or comparison asked for before using the data.','Multi-step reasoning':'Write the sequence of quantities and operations before calculating.'};breakthrough=strategies[skill]||strategies['Multi-step reasoning'];trap=`A common trap is doing a familiar operation before identifying what the question asks. Check the units and use this rule: ${breakthrough}`;
const grid=seed%7===0||['Fractions','Probability'].includes(skill);let choices:string[]|undefined,correct:number|string=answer;if(!grid){const vals=[answer];for(const v of [round(answer+a),round(answer-b),round(answer*2),round(answer+1),round(answer-1)])if(!vals.includes(v)&&vals.length<4)vals.push(v);while(vals.length<4)vals.push(answer+vals.length+19);const shift=seed%4;choices=vals.slice(shift).concat(vals.slice(0,shift)).map(String);correct=choices.indexOf(String(answer))}return{id:`math-${skill.toLowerCase().replaceAll(' ','-')}-${d}-${seed}-${variant}`,subject:'Math',skill,difficulty:d,text,choices,correct,type:grid?'grid':'mc',explanation,breakthrough,commonTrap:trap,distractorReasons:choices?.map((v,i)=>i===correct?'This follows the calculation.':`${v} does not follow the required sequence. ${explanation}`),templateId:template,generationMethod:'procedural-v1',estimatedTime:60+d*20,subskill:template}}
export function mathBatch(count=100,skill?:string,difficulty?:number,seed=1){return Array.from({length:count},(_,i)=>mathQuestion(skill||MATH_SKILLS[i%MATH_SKILLS.length],difficulty||i%5+1,seed+i,i%2))}
