import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const users=sqliteTable('users',{id:text('id').primaryKey(),username:text('username').notNull().unique(),name:text('name').notNull(),role:text('role').notNull(),state:text('state').notNull().default('active'),enrollment:text('enrollment').notNull().default('active'),grade:integer('grade').notNull().default(8),hash:text('hash').notNull(),sourceInquiry:text('source_inquiry').unique(),revokedBy:text('revoked_by'),revokedAt:integer('revoked_at'),revokeReason:text('revoke_reason'),mustChange:integer('must_change').notNull().default(1),created:integer('created').notNull()});
export const sessions=sqliteTable('sessions',{token:text('token').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),expires:integer('expires').notNull()},t=>[index('idx_sessions_user').on(t.userId)]);
export const classes=sqliteTable('classes',{id:text('id').primaryKey(),title:text('title').notNull(),description:text('description').notNull(),grade:integer('grade').notNull(),schedule:text('schedule').notNull().default(''),state:text('state').notNull().default('active'),visible:integer('visible').notNull().default(0),created:integer('created').notNull()});
export const memberships=sqliteTable('memberships',{id:text('id').primaryKey(),classId:text('class_id').notNull().references(()=>classes.id),userId:text('user_id').notNull().references(()=>users.id),kind:text('kind').notNull(),active:integer('active').notNull().default(1)},t=>[uniqueIndex('uniq_membership').on(t.classId,t.userId),index('idx_memberships_user').on(t.userId)]);
export const inquiries=sqliteTable('inquiries',{id:text('id').primaryKey(),name:text('name').notNull(),grade:integer('grade').notNull(),contact:text('contact').notNull(),phone:text('phone').notNull(),interest:text('interest').notNull(),message:text('message').notNull().default(''),status:text('status').notNull().default('new'),notes:text('notes').notNull().default(''),userId:text('user_id').references(()=>users.id),created:integer('created').notNull()});
export const assignments=sqliteTable('assignments',{id:text('id').primaryKey(),creator:text('creator').notNull().references(()=>users.id),classId:text('class_id').notNull().references(()=>classes.id),title:text('title').notNull(),instructions:text('instructions').notNull(),mode:text('mode').notNull(),subject:text('subject').notNull(),topic:text('topic').notNull(),grade:integer('grade').notNull(),count:integer('count').notNull(),items:text('items').notNull(),recipientSelection:text('recipient_selection').notNull().default('[]'),state:text('state').notNull().default('draft'),due:integer('due'),published:integer('published'),attemptLimit:integer('attempt_limit').notNull().default(1),minutes:integer('minutes').notNull().default(0),feedback:text('feedback').notNull().default('submission'),created:integer('created').notNull()});
export const recipients=sqliteTable('recipients',{id:text('id').primaryKey(),assignmentId:text('assignment_id').notNull().references(()=>assignments.id),userId:text('user_id').notNull().references(()=>users.id),due:integer('due'),attemptLimit:integer('attempt_limit')},t=>[uniqueIndex('uniq_recipient').on(t.assignmentId,t.userId),index('idx_recipients_user').on(t.userId)]);
export const attempts=sqliteTable('attempts',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),assignmentId:text('assignment_id').references(()=>assignments.id),title:text('title').notNull(),mode:text('mode').notNull(),grade:integer('grade').notNull(),items:text('items').notNull(),answers:text('answers').notNull(),cursor:integer('cursor').notNull().default(0),revision:integer('revision').notNull().default(0),state:text('state').notNull().default('in-progress'),started:integer('started').notNull(),deadline:integer('deadline'),finished:integer('finished'),released:integer('released').notNull().default(0),feedback:text('feedback').notNull().default(''),override:integer('override'),notes:text('notes').notNull().default('{}'),scoreJson:text('score_json'),conditions:text('conditions').notNull().default('{}')},t=>[index('idx_attempts_user').on(t.userId),index('idx_attempts_assignment').on(t.assignmentId),uniqueIndex('uniq_active_attempt').on(t.userId).where(sql`${t.state} = 'in-progress'`)]);
export const mistakes=sqliteTable('mistakes',{id:text('id').primaryKey(),attemptId:text('attempt_id').notNull().references(()=>attempts.id),userId:text('user_id').notNull().references(()=>users.id),itemIndex:integer('item_index').notNull(),reason:text('reason').notNull().default(''),reviewAt:integer('review_at').notNull(),stage:integer('stage').notNull().default(0)},t=>[uniqueIndex('uniq_mistake').on(t.attemptId,t.itemIndex),index('idx_mistakes_user').on(t.userId)]);
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),target:text('target').notNull(),created:integer('created').notNull()});
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const limits=sqliteTable('limits',{key:text('key').primaryKey(),hits:integer('hits').notNull(),expires:integer('expires').notNull()});
export const contentReviews=sqliteTable('content_reviews',{id:text('id').primaryKey(),state:text('state').notNull(),notes:text('notes').notNull(),actor:text('actor').notNull(),created:integer('created').notNull()});
export const reports=sqliteTable('reports',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),itemId:text('item_id').notNull(),message:text('message').notNull(),state:text('state').notNull().default('new'),created:integer('created').notNull()});
export const announcements=sqliteTable('announcements',{id:text('id').primaryKey(),classId:text('class_id').notNull().references(()=>classes.id),actor:text('actor').notNull(),message:text('message').notNull(),created:integer('created').notNull()});

export const customContent=sqliteTable('custom_content',{id:text('id').primaryKey(),owner:text('owner').notNull().references(()=>users.id),item:text('item').notNull(),created:integer('created').notNull()});

export const calibrations=sqliteTable('calibrations',{id:text('id').primaryKey(),grade:integer('grade').notNull(),payload:text('payload').notNull(),notes:text('notes').notNull(),actor:text('actor').notNull().references(()=>users.id),created:integer('created').notNull()},t=>[index('idx_calibrations_grade').on(t.grade,t.created)]);
export const exposures=sqliteTable('exposures',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),itemId:text('item_id').notNull(),source:text('source').notNull(),created:integer('created').notNull()},t=>[index('idx_exposures_user').on(t.userId,t.itemId)]);
